Repository ROCm/AMDMIGraphX, pull requests merged in 2020-04, with the labels that each got.

#489 fixed a bug in parse_slice
  src/onnx/onnx.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/slice_max_end_test.onnx
Labels: ort-blocker

#488 Add recip op for gpu
  src/onnx/onnx.cpp
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/device/recip.cpp
  src/targets/gpu/include/migraphx/gpu/device/recip.hpp
  src/targets/gpu/include/migraphx/gpu/recip.hpp
  src/targets/gpu/lowering.cpp
  test/cpu_ops_test.cpp
  test/gpu/ops_test.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/recip_test.onnx
Labels: ort-blocker

#498 Slice axes fix
  src/onnx/onnx.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/slice_3arg_test.onnx
Labels: ort-blocker

#499 Small bugs related to rnn
  src/driver/verify.cpp
  src/rewrite_rnn.cpp
  src/targets/gpu/include/migraphx/gpu/gemm.hpp
  test/gpu/ops_test.cpp
Labels: ort-blocker

#502 Add OneHot op
  src/onnx/onnx.cpp
  test/onnx/gen_onnx.py
  test/onnx/onehot_test.onnx
  test/onnx/onnx_test.cpp
  test/tf/gen_tf_pb.py
Labels: onnx, ort-blocker

#500 Make contiguous preserve scalar shape
  Jenkinsfile
  src/include/migraphx/op/contiguous.hpp
  src/shape.cpp
  test/op_shape_test.cpp
  test/shape_test.cpp
Labels: ort-blocker

#497 Fix bug with transpose and pad
  src/targets/gpu/pad.cpp
  test/gpu/ops_test.cpp
Labels: ort-blocker

#503 Fix bug in eliminate concat: dont use sorted allocations to assign offsets
  src/eliminate_concat.cpp
  test/eliminate_concat_test.cpp
Labels: ort-blocker

#490 Segment fault c api
  src/api/include/migraphx/migraphx.hpp
  test/api/test_cpu.cpp
Labels: ort-blocker

#510 Onehot operator
  src/onnx/onnx.cpp
  test/onnx/gen_onnx.py
  test/onnx/onehot_test.onnx
  test/onnx/onnx_test.cpp
Labels: ort-blocker

#474 Parse onnx using explicit input shape
  src/api/api.cpp
  src/api/include/migraphx/migraphx.h
  src/api/include/migraphx/migraphx.hpp
  src/api/migraphx.py
  src/include/migraphx/onnx.hpp
  src/onnx/onnx.cpp
  src/py/migraphx_py.cpp
  test/api/test_cpu.cpp
  test/onnx/onnx_test.cpp
  tools/api/api.cpp
  tools/api/migraphx.h
Labels: ort-blocker

#513 Add tile op
  src/onnx/onnx.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/tile_test.onnx
  test/onnx/tile_test_3x2.onnx
Labels: onnx
