Repository ROCm/AMDMIGraphX, pull requests merged in 2023-03, with the labels that each got.

#1586 Updates some compiler pass docs
  src/include/migraphx/memory_coloring.hpp
  src/include/migraphx/replace_allocate.hpp
  src/targets/gpu/include/migraphx/gpu/lowering.hpp
Labels: documentation, simple, skip performance check, skip bot checks

#1592 Use migraphx-benchmark repo for updating ROCm image for CI actions
  .github/workflows/rocm-image-release.yaml
Labels: skip bot checks

#1591 move default to migx 5.6 project
  .github/workflows/add-to-project.yaml
Labels: skip bot checks

#1581 Update rocm-cmake and half package URL
  CMakeLists.txt
  dev-requirements.txt
  requirements.txt
  src/include/migraphx/half.hpp
  test/onnx/verify_onnx.cpp
Labels: dependencies

#1599 Remove install_deps.cmake
  install_deps.cmake
Labels: simple, skip performance check

#1611 [Cleanup] Suppress warnings for msgpack-cxx and remove old memory coloring passes
  src/CMakeLists.txt
  src/eliminate_allocation.cpp
  src/include/migraphx/pass_config.hpp
  src/opt/memory_coloring.cpp
  src/opt/memory_coloring_impl.cpp
  src/opt/memory_coloring_impl.hpp
Labels: simple

#1617 Update GH actions to use GITHUB_OUTPUT
  .github/workflows/ci.yaml
Labels: simple, skip performance check, skip bot checks

#1620 Use `lld` instead of `gold` linker in GH actions
  .github/workflows/ci.yaml
Labels: simple, skip performance check, skip bot checks

#1626 Fold const on last instruction
  src/propagate_constant.cpp
  test/propagate_constant_test.cpp
  test/verify/test_gather_literal_inputs.cpp
Labels: bugfix

#1635 Fix default target in driver
  src/driver/CMakeLists.txt
  src/driver/main.cpp
Labels: bugfix, high priority

#1637 Add Additional flags to accuracy_checker.py
  tools/accuracy/accuracy_checker.py
Labels: enhancement, roadmap, onnxruntime

#1623 Remove `/opt/rocm/hip` paths as part of ROCm file-org change
  examples/migraphx/cpp_parse_load_save/CMakeLists.txt
  examples/migraphx/custom_op_miopen_kernel/CMakeLists.txt
  examples/migraphx/custom_op_rocblas_kernel/CMakeLists.txt
  examples/vision/cpp_mnist/CMakeLists.txt
  src/targets/gpu/CMakeLists.txt
Labels: simple, skip performance check, skip bot checks

#1639 Remove version name from check_context
  examples/migraphx/migraphx_driver/README.md
  src/include/migraphx/check_context.hpp
  src/py/migraphx_py.cpp
  src/targets/gpu/include/migraphx/gpu/oper.hpp
  src/targets/gpu/include/migraphx/gpu/prefix_scan_sum.hpp
  src/targets/gpu/include/migraphx/gpu/reduce_op.hpp
Labels: high priority

#1653 Fix bug when concatting with the vectorization axis
  src/targets/gpu/jit/concat.cpp
  test/verify/test_concat_axis_2.cpp
Labels: bugfix, high priority
