Repository ROCm/AMDMIGraphX, pull requests merged in 2023-06, with the labels that each got.

#1779 Convert Fp16 instance-norm to FP32 temporarily
  src/onnx/parse_instancenorm.cpp
  test/onnx/onnx_test.cpp
  test/verify/main.cpp
  test/verify/test_instancenorm.cpp
  test/verify/verify_program.hpp
Labels: high priority

#1810 Conditionally enable GeLU approximation
  src/targets/gpu/target.cpp
Labels: high priority, simple

#1824 Add missing specialization for the `nullptr` for the hash function
  src/targets/gpu/jit/ck_gemm.cpp
  src/value.cpp
Labels: high priority

#1825 Fix compile warnings for shadowing variable names
  src/include/migraphx/matcher.hpp
Labels: bugfix

#1787 Fix shape typo in API test
  test/api/test_gpu.cpp
Labels: bugfix, simple

#1802 Print message from driver if offload copy is set for compiled program
  src/driver/main.cpp
  src/driver/perf.cpp
  src/driver/perf.hpp
Labels: enhancement

#1814 Revert "Handle broadcasts across dot and concat (#1689) (#1731)"
  src/normalize_attributes.cpp
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: bugfix, high priority

#1835 Fix TRACE_EVAL > 1
  src/program.cpp
  src/targets/gpu/hip.cpp
Labels: bugfix

#1715 fix parse_instancenorm to create broadcast and multibroadcast instruc…
  src/common.cpp
  src/include/migraphx/op/broadcast.hpp
  src/include/migraphx/op/multibroadcast.hpp
  src/include/migraphx/shape.hpp
  src/onnx/onnx_parser.cpp
  src/onnx/parse_instancenorm.cpp
  test/onnx/gen_onnx.py
  test/onnx/instance_norm_dyn_batch_half_test.onnx
  test/onnx/instance_norm_dyn_batch_test.onnx
  test/onnx/onnx_test.cpp
  test/onnx/verify_onnx.cpp
  test/op_shape_test.cpp
Labels: onnx, bugfix, simple

#1804 Fallback on C arrays for add_embed_library on non-linux builds
  cmake/Embed.cmake
Labels: roadmap, high priority

#1836 2+ input multibroadcast and 2+ input dynamic shape insert_common_op
  src/common.cpp
  src/include/migraphx/common.hpp
  src/include/migraphx/op/broadcast.hpp
  src/include/migraphx/op/multibroadcast.hpp
  test/op_shape_test.cpp
  test/ref_ops_test.cpp
Labels: enhancement, roadmap, dependencies

#1840 Fix convert operation for NaNs
  src/include/migraphx/op/convert.hpp
  src/include/migraphx/shape.hpp
  test/ref_ops_test.cpp
Labels: bugfix, simple

#1838 Add trace for SIMPLIFY_ALGEBRA matches
  src/include/migraphx/matcher.hpp
  src/simplify_algebra.cpp
Labels: enhancement

#1864 Print max,min,mean and stddev values for TRACE_EVAL = 2
  src/program.cpp
Labels: skip bot checks

#1898 fix formatting
  src/targets/gpu/mlir.cpp
Labels: skip bot checks

#1858 Add a MIGRAPHX_TRACE_MATCHES_FOR env variable to filter the matcher trace
  src/include/migraphx/matcher.hpp
  src/include/migraphx/source_location.hpp
  src/simplify_algebra.cpp
Labels: enhancement

#1907 Remove reduce
  src/program.cpp
Labels: skip bot checks
