Repository ROCm/AMDMIGraphX, pull requests merged in 2023-05, with the labels that each got.

#1689 Handle broadcasts across dot and concat
  src/normalize_attributes.cpp
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: enhancement

#1712 Update C/C++ API for dynamic batch
  src/api/api.cpp
  src/api/include/migraphx/migraphx.h
  src/api/include/migraphx/migraphx.hpp
  src/api/migraphx.py
  test/api/CMakeLists.txt
  test/api/test_dynamic_shape.cpp
  test/api/test_gpu.cpp
  test/ref_ops_test.cpp
  tools/api.py
  tools/api/api.cpp
Labels: high priority

#1732 Driver improvements to supported ops
  src/driver/main.cpp
  src/include/migraphx/tf.hpp
  src/onnx/op_parser.cpp
  src/tf/op_parser.cpp
  src/tf/tf.cpp
Labels: enhancement, simple

#1728 Dynamic batch C++ API example
  examples/migraphx/cpp_dynamic_batch/CMakeLists.txt
  examples/migraphx/cpp_dynamic_batch/README.md
  examples/migraphx/cpp_dynamic_batch/add_scalar_test.onnx
  examples/migraphx/cpp_dynamic_batch/dynamic_batch.cpp
Labels: roadmap, documentation

#1753 unsqueeze support for broadcasted scalars
  src/include/migraphx/op/unsqueeze.hpp
  test/op_shape_test.cpp
Labels: enhancement, simple

#1729 adjust docker files to support new rocm 5.5
  CMakeLists.txt
  Dockerfile
  hip-clang.docker
  src/include/migraphx/auto_any_cast.hpp
  src/include/migraphx/check_shapes.hpp
  src/include/migraphx/reflect.hpp
  src/onnx/parse_instancenorm.cpp
  src/onnx/parse_mean.cpp
  src/onnx/parse_randomnormal_ops.cpp
  src/onnx/parse_randomuniform_ops.cpp
  src/targets/fpga/include/migraphx/fpga/vitis_ai_adapter.hpp
  src/targets/fpga/vitis_ai_adapter.cpp
  src/targets/gpu/compile_hip.cpp
  src/targets/gpu/compile_hip_code_object.cpp
  src/targets/gpu/include/migraphx/gpu/compile_hip.hpp
  test/CMakeLists.txt
  test/gpu/jit.cpp
Labels: roadmap

#1763 update to v0.11.0 of rocm-docs-core
  docs/.sphinx/requirements.in
  docs/.sphinx/requirements.txt
  docs/conf.py
Labels: documentation

#1764 Use half HIP APIs to compute max and min
  src/targets/gpu/kernels/include/migraphx/kernels/math.hpp
  test/verify/test_min_max.cpp
Labels: simple

#1733 Readme update
  .github/workflows/README.md
Labels: skip bot checks

#1739 Change compiler_replace to a class that stores the code objects directly
  src/targets/gpu/compile_ops.cpp
  src/targets/gpu/include/migraphx/gpu/compiler.hpp
  src/targets/gpu/jit/concat.cpp
  src/targets/gpu/jit/gather.cpp
  src/targets/gpu/jit/gathernd.cpp
  src/targets/gpu/jit/layernorm.cpp
  src/targets/gpu/jit/mlir.cpp
  src/targets/gpu/jit/pad.cpp
  src/targets/gpu/jit/pointwise.cpp
  src/targets/gpu/jit/reduce.cpp
  src/targets/gpu/jit/roialign.cpp
  src/targets/gpu/jit/scatternd.cpp
  src/targets/gpu/jit/softmax.cpp
Labels: enhancement

#1758 Update cpp generator to handle inf from float
  src/cpp_generator.cpp
  test/verify/test_literal_limits.cpp
Labels: bugfix

#1755 Add option to use type erased matchers to reduce symbol names
  src/include/migraphx/matcher.hpp
Labels: bugfix

#1710 Improvements to driver output
  src/module.cpp
  src/program.cpp
  test/print_graph_test.cpp
Labels: enhancement

#1789 Check if generate files are different
  Jenkinsfile
Labels: skip bot checks
