Repository ROCm/AMDMIGraphX, pull requests merged in 2023-09, with the labels that each got.

#2153 Fixed test float equal for Windows
  test/float_equal.cpp
Labels: Windows

#2154 Fixed stringutils test
  src/include/migraphx/stringutils.hpp
Labels: Windows

#2103 Add environment variable to enable mlir exhaustive tuning configs
  src/targets/gpu/mlir.cpp
Labels: skip bot checks

#2176 add `continue_on_error` for cache clearing
  .github/workflows/ci.yaml
Labels: skip bot checks

#1949 Stamp driver to read the SHA-1 of .onnxrt-commit
  src/CMakeLists.txt
  src/driver/CMakeLists.txt
  src/driver/main.cpp
Labels: enhancement, simple, skip bot checks, Continous Integration

#2068 Add chunking of binaries when writing with msgpack
  .github/workflows/ci.yaml
  src/msgpack.cpp
  src/program.cpp
  test/CMakeLists.txt
  test/msgpack.cpp
Labels: enhancement, bugfix

#2082 Print warning about miopen_fusion while generating mxr
  src/driver/main.cpp
  src/load_save.cpp
  src/verify_args.cpp
Labels: skip bot checks

#2182 Add fp16 flag to test runner to check models quantized to fp16
  tools/test_runner.py
Labels: high priority, Continous Integration

#2185 Preserve layout of fused kernel for `layernorm+pointwise`
  src/targets/gpu/prefuse_ops.cpp
  test/verify/test_layernorm.cpp
Labels: enhancement, bugfix

#2087 `fill` ref operator
  src/CMakeLists.txt
  src/include/migraphx/check_shapes.hpp
  src/include/migraphx/op/fill.hpp
  src/include/migraphx/operators.hpp
  test/op_shape_test.cpp
  test/ref/fill.cpp
Labels: roadmap, high priority

#2146 Rework split_reshape simplification to handle multiple reshapes from same slice
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: enhancement, roadmap, high priority, TorchMIGraphX

#2204 Disable Python 2.7 version in PythonModules.cmake
  cmake/PythonModules.cmake
Labels: Continous Integration

#2214 Rectify flipped coordinate_transformation_mode logic in ROIAlign #2159
  src/include/migraphx/op/roialign.hpp
  src/onnx/parse_roialign.cpp
  src/targets/gpu/jit/roialign.cpp
  test/onnx/onnx_test.cpp
  test/ref/roialign.cpp
Labels: roadmap, bugfix, Continous Integration

#2195 Optimize broadcast+transpose for scalars
  src/optimize_module.cpp
  src/propagate_constant.cpp
  src/simplify_reshapes.cpp
  test/optimize_module_test.cpp
  test/simplify_reshapes_test.cpp
Labels: bugfix, high priority

#2166 Enable tests package
  CMakeLists.txt
  dev-requirements.txt
  test/CMakeLists.txt
  test/ref/CMakeLists.txt
  test/verify/CMakeLists.txt
Labels: roadmap, skip bot checks, Continous Integration, Windows

#2238 update ORT to 9/22
  test/onnx/.onnxrt-commit
Labels: onnxruntime, Continous Integration

#2218 Improvements to GH Actions in our CI
  .github/workflows/ci.yaml
Labels: skip bot checks, Continous Integration

#2217 Bump onnx from 1.10.2 to 1.14.0 #2121
  test/py/onnx_backend_test.py
  tools/download_models.sh
  tools/install_prereqs.sh
Labels: onnx, Continous Integration

#2161 create simplify_dyn_ops pass and add variable slice optimization
  src/CMakeLists.txt
  src/include/migraphx/simplify_dyn_ops.hpp
  src/simplify_dyn_ops.cpp
  src/split_single_dyn_dim.cpp
  src/targets/gpu/target.cpp
  test/simplify_dyn_ops_test.cpp
  test/split_single_dyn_dim_test.cpp
Labels: enhancement, roadmap

#2245 Add rbuild profile for Performance tests
  rbuild.ini
Labels: bugfix, Continous Integration

#2247 Add continue-on-error:true for CI
  .github/workflows/ci.yaml
Labels: bugfix, Continous Integration

#2189 Ignore order of arguments while doing layernorm + pointwise fusion
  src/targets/gpu/fuse_ops.cpp
  test/gpu/fuse_ops.cpp
  test/include/pointwise.hpp
Labels: roadmap, bugfix, simple

#2149 Dont insert reshapes when converting pooling to reduce
  src/rewrite_pooling.cpp
  src/simplify_reshapes.cpp
  test/rewrite_pooling_test.cpp
  test/verify/test_reduce_add.cpp
  test/verify/test_reduce_noop_add.cpp
Labels: enhancement

#2260 Add missing continue-on-error:true flag for jlumbroso/free-disk-space…
  .github/workflows/ci.yaml
Labels: bugfix, skip bot checks, Continous Integration

#2259 Add the recommended depend install location to gitignore.
  .gitignore
Labels: skip bot checks

#2248 Force Onnxruntime build pipe to use mi100+ and no cdna
  Jenkinsfile
Labels: bugfix, Continous Integration

#2258 Fix shapes check for allocate
  src/include/migraphx/op/allocate.hpp
  test/op_shape_test.cpp
Labels: simple

#2234 Add an error message when gpu_targets is not set
  .github/workflows/ci.yaml
  src/targets/gpu/CMakeLists.txt
Labels: high priority, skip bot checks, Continous Integration

#2201 ROCm 5.7 CI update
  .github/workflows/benchmark.yaml
  .github/workflows/performance.yaml
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  hip-clang.docker
  src/targets/gpu/fuse_mlir.cpp
  tools/docker/sles.docker
  tools/docker/ubuntu_2204.dockerfile
Labels: roadmap, high priority, Continous Integration

#2184 Enable MLIR to be built with MIGraphX
  .github/workflows/ci.yaml
  Dockerfile
  hip-clang.docker
  mlir-requirements.txt
  requirements.txt
  src/targets/gpu/CMakeLists.txt
Labels: roadmap

#2251 Changes for the CK + HIPRTC
  Jenkinsfile
  requirements.txt
  src/targets/gpu/compile_hip.cpp
Labels: skip bot checks
