Repository ROCm/AMDMIGraphX, pull requests merged in 2023-10, with the labels that each got.

#2265 Fix Jenkinsfile failure
  Jenkinsfile
Labels: skip bot checks

#2269 Add gfx906 target to Jenkins
  Jenkinsfile
Labels: skip bot checks

#2272 Reset HIP status using `hipGetLastError()`
  src/targets/gpu/device/include/migraphx/gpu/device/launch.hpp
Labels: skip bot checks

#2111 Dynamic ConstantOfShape
  src/onnx/parse_constant_of_shape.cpp
  test/onnx/const_of_shape_default_test.onnx
  test/onnx/const_of_shape_dyn_float_test.onnx
  test/onnx/const_of_shape_dyn_int64_test.onnx
  test/onnx/const_of_shape_empty_input_test.onnx
  test/onnx/const_of_shape_float_test.onnx
  test/onnx/const_of_shape_int64_test.onnx
  test/onnx/const_of_shape_no_value_attr_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
Labels: roadmap, high priority

#2273 update version after branch
  CMakeLists.txt
Labels: skip bot checks

#2261 Add support for CastLike operator
  src/onnx/parse_castlike.cpp
  test/onnx/castlike_error_test.onnx
  test/onnx/castlike_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/py/onnx_backend_test.py
Labels: roadmap, onnx

#2283 fix call to std::isfinite() on Windows
  src/cpp_generator.cpp
  src/include/migraphx/op/convert.hpp
  src/include/migraphx/op/isnan.hpp
  src/include/migraphx/verify.hpp
  src/program.cpp
Labels: roadmap, dependencies, Windows

#2264 Specify full path for libamdhip64.so
  test/py/test_gpu_async.py
Labels: bug, SLES

#2298 Set compile options from accuracy checker
  tools/accuracy/accuracy_checker.py
Labels: enhancement, simple

#1999 prepare for Windows resources with resource script files
  cmake/Embed.cmake
  src/compile_src.cpp
  src/include/migraphx/compile_src.hpp
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_hip.cpp
  src/targets/gpu/compile_hip_code_object.cpp
  src/targets/gpu/include/migraphx/gpu/compile_hip.hpp
  src/targets/gpu/jit/ck_gemm.cpp
  test/gpu/jit.cpp
  test/gpu/stream_sync.cpp
  test/jit.cpp
  test/multi_target/multitarget_test.cpp
Labels: skip bot checks, Windows

#2301 Add explanatory documentation to `allocate`
  src/include/migraphx/op/allocate.hpp
Labels: simple

#2155 Added fix for test_msgpack_float and test_msgpack_object
  test/msgpack.cpp
Labels: Windows

#2281 add missing DLL symbol exports
  src/include/migraphx/normalize_attributes.hpp
  src/include/migraphx/pad_calc.hpp
  src/targets/gpu/device/targets.hpp.in
Labels: skip bot checks, Windows

#2300 Run optimize_module for int8 quantization
  src/quantization.cpp
Labels: enhancement, roadmap, high priority

#2061 Windows: Fix instruction_ref iterator issues in debug builds
  src/include/migraphx/instruction_ref.hpp
Labels: Windows

#2277 port class 'process' to Windows
  src/process.cpp
Labels: Windows

#2279 remove disabling execptions from production build
  CMakeLists.txt
  src/api/CMakeLists.txt
  src/api/api.cpp
  tools/api/api.cpp
Labels: skip bot checks, Windows

#2280 make pybind compilation optional
  CMakeLists.txt
  src/CMakeLists.txt
  src/driver/CMakeLists.txt
  src/driver/main.cpp
  src/py/CMakeLists.txt
Labels: Windows

#2284 fix compilation of uniform int distribution
  src/include/migraphx/op/random_uniform.hpp
Labels: Windows

#2286 wrap lambda to support Windows
  src/targets/cpu/include/migraphx/cpu/dnnl.hpp
Labels: Windows

#2305 edit in tools check_stamped
  tools/check_stamped.py
Labels: Cleanup

#2282 a few c++ fixes to allow compilation on Windows
  src/api/api.cpp
  src/api/include/migraphx/migraphx.h
  src/api/include/migraphx/migraphx.hpp
  src/include/migraphx/auto_register.hpp
  src/include/migraphx/config.hpp
  src/include/migraphx/filesystem.hpp
  src/include/migraphx/float_equal.hpp
  src/include/migraphx/generate.hpp
  src/include/migraphx/instruction_ref.hpp
  src/include/migraphx/matcher.hpp
  src/include/migraphx/op/nonmaxsuppression.hpp
  src/include/migraphx/op/roialign.hpp
  src/include/migraphx/optional.hpp
  src/include/migraphx/run_loop.hpp
  src/include/migraphx/source_location.hpp
  src/include/migraphx/type_name.hpp
  src/onnx/onnx_parser.cpp
  src/targets/cpu/include/migraphx/cpu/pointwise.hpp
  src/targets/gpu/hiprtc/main.cpp
  test/include/test.hpp
  test/verify/run_verify.cpp
  tools/api/api.cpp
  tools/api/migraphx.h
Labels: skip bot checks, Windows

#2278 port class 'dynamic_loader' to Windows
  src/dynamic_loader.cpp
  src/include/migraphx/dynamic_loader.hpp
  src/include/migraphx/instruction_ref.hpp
  src/include/migraphx/tmp_dir.hpp
Labels: Windows

#2288 python: add 'make generate' OS agnostic
  tools/CMakeLists.txt
  tools/api.py
  tools/generate.py
  tools/generate.sh
  tools/te.py
Labels: skip bot checks, Windows

#2320 clang-format needed for build
  Jenkinsfile
  tools/CMakeLists.txt
Labels: Continous Integration

#2310 fp16 change default tolerances for driver verify
  src/driver/main.cpp
Labels: roadmap, simple

#2316 Remove try-except clause for importing numpy in tests
  test/py/test_gpu.py
  test/py/test_numpy.py
Labels: Continous Integration

#2327 fix missing exports on Windows
  src/targets/cpu/include/migraphx/cpu/fuse_ops.hpp
  src/targets/gpu/include/migraphx/gpu/fuse_ops.hpp
  src/targets/gpu/include/migraphx/gpu/prefuse_ops.hpp
Labels: skip bot checks, Windows

#2271 Optimize broadcast + transpose for nonscalars
  src/simplify_algebra.cpp
  src/simplify_reshapes.cpp
  test/optimize_module_test.cpp
  test/simplify_algebra_test.cpp
  test/simplify_reshapes_test.cpp
Labels: enhancement, dependencies, Matchers

#2308 QLinearMatMul
  src/onnx/parse_qlinearmatmul.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/qlinearmatmul_1D_test.onnx
  test/onnx/qlinearmatmul_2D_test.onnx
  test/onnx/qlinearmatmul_3D_test.onnx
  test/onnx/verify_onnx.cpp
Labels: roadmap, Onnx Operators

#2304 2 Input Reshape `ref` implementation
  src/include/migraphx/op/reshape.hpp
  src/onnx/parse_reshape.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/reshape_variable_input_dyn_test.onnx
  test/onnx/reshape_variable_input_test.onnx
  test/op_shape_test.cpp
  test/ref/reshape.cpp
Labels: enhancement, roadmap

#2240 Add support for Shrink ONNX operator
  src/onnx/parse_shrink.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/shrink_hard_test.onnx
  test/onnx/shrink_int8_test.onnx
  test/onnx/shrink_soft_test.onnx
  test/onnx/shrink_uint8_test.onnx
  test/onnx/shrink_verify2_test.onnx
  test/onnx/shrink_verify_test.onnx
  test/onnx/verify_onnx.cpp
  test/py/onnx_backend_test.py
  test/verify/test_shrink.cpp
Labels: onnx

#2348 Update accuracy checker to support --disable-offload-copy
  tools/accuracy/accuracy_checker.py
Labels: bugfix, simple

#2167 Add flag to accept non-uniform WG sizes
  src/targets/gpu/compile_hip_code_object.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/index.hpp
Labels: enhancement, bugfix

#2346 Make argument constructor explicit
  src/include/migraphx/argument.hpp
  src/include/migraphx/op/allocate.hpp
  src/include/migraphx/op/pooling.hpp
  src/targets/gpu/include/migraphx/gpu/convolution.hpp
  test/eliminate_allocation_test.cpp
  test/eliminate_concat_test.cpp
  test/memory_coloring_test.cpp
  test/normalize_ops_test.cpp
  test/replace_allocate.cpp
Labels: bugfix

#2235 Add support for select_last_index attribute for ArgMax & ArgMin
  src/include/migraphx/op/argmax.hpp
  src/include/migraphx/op/argmin.hpp
  src/onnx/parse_arg_op.cpp
  src/targets/gpu/argmax.cpp
  src/targets/gpu/argmin.cpp
  src/targets/gpu/device/argmax.cpp
  src/targets/gpu/device/argmin.cpp
  src/targets/gpu/include/migraphx/gpu/device/arg_op.hpp
  src/targets/gpu/include/migraphx/gpu/device/argmax.hpp
  src/targets/gpu/include/migraphx/gpu/device/argmin.hpp
  test/onnx/argmax_select_last_index_test.onnx
  test/onnx/argmin_select_last_index_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/py/onnx_backend_test.py
  test/ref/argmax.cpp
  test/ref/argmin.cpp
  test/verify/test_arg_ops.cpp
Labels: onnx

#2375 Bump MIGraphX version
  CMakeLists.txt
Labels: simple

#2384 use find_package() for SQLite3
  src/CMakeLists.txt
Labels: skip bot checks, Windows

#2383 make CK JIT optional
  CMakeLists.txt
  src/targets/gpu/CMakeLists.txt
  test/CMakeLists.txt
Labels: Windows

#2371 Disable fuse_mlir test if MLIR is not enabled
  test/gpu/fuse_mlir.cpp
Labels: simple

#2344 Added fix for test_targets on Windows
  test/CMakeLists.txt
  test/targets.cpp
Labels: skip bot checks, Windows

#2362 fix tests and error cases; allow std::optional for streamutils
  src/include/migraphx/op/allocate.hpp
  src/include/migraphx/streamutils.hpp
  test/op_shape_test.cpp
  test/ref/allocate.cpp
Labels: bugfix, simple

#2369 Use an older version of numpy for compatibility with Python3.6
  test/py/requirements.txt
Labels: dependencies, simple

#2331 Add flag to control virtual environments
  Jenkinsfile
  test/py/CMakeLists.txt
Labels: enhancement, Continous Integration

#2388 Fix allocate 0 arg version
  src/include/migraphx/op/allocate.hpp
  test/op_shape_test.cpp
Labels: bugfix, simple

#2387 Run simplify_qdq first before optimize_module
  src/quantization.cpp
Labels: bugfix, high priority
