Repository ROCm/AMDMIGraphX, pull requests merged in 2023-08, with the labels that each got.

#2023 Disable use of linker temporarily to fix cmake order problem
  cmake/Embed.cmake
Labels: high priority

#2028 Use free regular_file function for SLES which uses experimental files…
  src/py/py_loader.cpp
Labels: high priority, skip bot checks

#2005 Add use of implicit deps inside sorting function
  src/include/migraphx/module.hpp
  src/module.cpp
  src/program.cpp
  test/module_test.cpp
Labels: bugfix

#2053 Remove gcnArch usage
  src/targets/gpu/device_name.cpp
  src/targets/gpu/include/migraphx/gpu/context.hpp
  src/targets/gpu/include/migraphx/gpu/device_name.hpp
Labels: skip bot checks

#2048 Add builds for sles in github actions
  .github/workflows/ci.yaml
  src/include/migraphx/algorithm.hpp
  tools/docker/sles.docker
  tools/install_prereqs.sh
Labels: enhancement, roadmap, Continous Integration, SLES

#2049 Add a check for inclusion of windows.h header
  test/CMakeLists.txt
Labels: dependancies, Continous Integration, Windows

#2066 Check for device kernel launch error message
  src/targets/gpu/device/include/migraphx/gpu/device/launch.hpp
Labels: skip bot checks

#2086 Remove operators.hpp includes
  src/memory_coloring.cpp
  test/eliminate_pad_test.cpp
  test/gpu/quantization.cpp
  test/inline_module_test.cpp
  test/insert_pad_test.cpp
  test/layout_nhwc.cpp
  test/onnx/onnx_rnn_test.cpp
  test/onnx/verify_onnx.cpp
  test/op_shape_test.cpp
  test/pad_calc_test.cpp
  test/quantization.cpp
  test/simplify_algebra_test.cpp
  test/simplify_reshapes_test.cpp
  test/verify/gemm_literal.cpp
Labels: dependencies

#2090 Add 'skip bot checks' label to Onnxruntime Weekly Sync PR workflow
  .github/workflows/sync-onnxrt-main.yaml
Labels: enhancement, skip bot checks, Continous Integration

#2100 Fix slice error when data input is constant
  src/onnx/parse_slice.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/slice_constant_test.onnx
Labels: bugfix

#2108 Add --build_wheel flag to build_and_test_onnxrt.sh
  tools/build_and_test_onnxrt.sh
Labels: roadmap, onnxruntime, simple, skip bot checks

#2127 Use matcher name for the `TRACE_MATCHES_FOR`
  src/include/migraphx/matcher.hpp
Labels: skip bot checks

#2050 Check that migraphx_gpu is not using device compilation in migraphx_gpu
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/no_device.cpp
Labels: bugfix, dependencies, skip bot checks
