Repository ROCm/AMDMIGraphX, pull requests merged in 2023-02, with the labels that each got.

#1550 Migrate to Docker Layer Caching2
  .github/workflows/ci.yaml
Labels: skip bot checks

#1548 Update matcher to better match layernorm fusions in other models
  src/include/migraphx/match/layernorm.hpp
  src/simplify_algebra.cpp
  src/targets/gpu/include/migraphx/gpu/prefuse_ops.hpp
  src/targets/gpu/prefuse_ops.cpp
  test/simplify_algebra_test.cpp
Labels: bugfix, high priority

#1461 Add disable tests for one case that breaks in onnx v1.12.0
  .github/workflows/ci.yaml
  test/py/onnx_backend_test.py
Labels: bugfix, dependencies

#1564 Requirements.txt obselete, now split into different requirements files
  tools/build_and_test_onnxrt.sh
Labels: onnxruntime, skip performance check, skip bot checks

#1519 Add flag for tuning in migraphx-driver
  doc/src/dev_intro.rst
  doc/src/driver/compile.rst
  doc/src/reference/py.rst
  examples/migraphx/migraphx_driver/README.md
  src/api/api.cpp
  src/api/include/migraphx/migraphx.h
  src/api/include/migraphx/migraphx.hpp
  src/api/migraphx.py
  src/driver/main.cpp
  src/driver/perf.cpp
  src/driver/perf.hpp
  src/include/migraphx/compile_options.hpp
  src/include/migraphx/context.hpp
  src/program.cpp
  src/py/migraphx_py.cpp
  src/targets/gpu/include/migraphx/gpu/context.hpp
  src/targets/gpu/include/migraphx/gpu/convolution.hpp
  src/targets/gpu/include/migraphx/gpu/miopen.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/target.cpp
  test/api/test_gpu.cpp
  test/py/test_gpu.py
  tools/api/api.cpp
  tools/include/context.hpp
  tools/te.py
Labels: enhancement

#1546 Remove HCC
  .clang-tidy
  CMakeLists.txt
  Jenkinsfile
  install_deps.cmake
  src/compile_src.cpp
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_hip.cpp
  src/targets/gpu/device/include/migraphx/gpu/device/launch.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/hip.hpp
  tools/build_and_test_onnxrt.sh
Labels: enhancement

#1574 Added human readable Changelog to the project
  CHANGELOG.md
Labels: skip bot checks
