Repository ROCm/AMDMIGraphX, pull requests merged in 2023-07, with the labels that each got.

#1687 Add flag to trace onnx parser
  src/onnx/onnx_parser.cpp
Labels: simple

#1862 Dynamic shape ref `clip` operator
  src/common.cpp
  src/include/migraphx/op/clip.hpp
  test/onnx/clip_dyn_min_max_test.onnx
  test/onnx/clip_dyn_min_only_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/ref_ops_test.cpp
Labels: simple

#1910 Fix literal rounding in codegen functions
  src/include/migraphx/raw_data.hpp
  test/gpu/codegen_literal.cpp
  test/literal_test.cpp
Labels: bugfix, simple

#1751 Enable eval to handle multiple contexts
  src/CMakeLists.txt
  src/include/migraphx/instruction.hpp
  src/include/migraphx/module.hpp
  src/include/migraphx/operation.hpp
  src/include/migraphx/program.hpp
  src/include/migraphx/target.hpp
  src/instruction.cpp
  src/module.cpp
  src/program.cpp
  src/target.cpp
  test/dead_code_elimination_test.cpp
  test/eliminate_identity_test.cpp
  test/eval_test.cpp
  test/include/basic_ops.hpp
  test/propagate_constant_test.cpp
  test/validate.cpp
  tools/include/operation.hpp
  tools/include/target.hpp
Labels: enhancement, roadmap

#1918 Use MIGRAPHX_GLOBAL
  src/targets/gpu/jit/ck_gemm.cpp
  src/targets/gpu/jit/concat.cpp
  src/targets/gpu/jit/gather.cpp
  src/targets/gpu/jit/gathernd.cpp
  src/targets/gpu/jit/layernorm.cpp
  src/targets/gpu/jit/pad.cpp
  src/targets/gpu/jit/pointwise.cpp
  src/targets/gpu/jit/reduce.cpp
  src/targets/gpu/jit/roialign.cpp
  src/targets/gpu/jit/scatternd.cpp
  src/targets/gpu/jit/softmax.cpp
Labels: enhancement, simple

#1897 Try ROCm Runner
  .github/workflows/ci.yaml
Labels: skip bot checks

#1874 Remove cached docker images from Github Runners
  .github/workflows/ci.yaml
Labels: enhancement, skip bot checks, Continous Integration

#1823 Pooling op. calculation changes
  src/include/migraphx/op/pooling.hpp
  test/ref_ops_test.cpp
  test/verify/test_avg_pooling_pad.cpp
Labels: enhancement, bugfix

#1924 [NFC] Update MLIR usage to account for upstream merge
  Dockerfile
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/mlir.cpp
Labels: skip bot checks

#1932 Simplify nested reshapes
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: enhancement, bugfix, Matchers

#1970 Default to ROCm 5.6
  .github/workflows/performance.yaml
Labels: skip bot checks

#1976 Make global workitems multiple of local workitems
  .github/workflows/ci.yaml
  Jenkinsfile
  src/targets/gpu/compile_hip_code_object.cpp
Labels: high priority

#1974 Use `optimize_module` pass for the quantization to fp16
  src/onnx/parse_batchnorm.cpp
  src/quantization.cpp
  src/tf/parse_batchnorm.cpp
  test/onnx/onnx_test.cpp
  test/quantization.cpp
  test/tf/tf_test.cpp
Labels: high priority

#1969 Add back clamping and add tests
  Jenkinsfile
  src/include/migraphx/op/convert.hpp
  test/api/test_gpu.cpp
  test/py/test_gpu.py
  test/ref_ops_test.cpp
Labels: bugfix, high priority

#1967 Use /opt/rocm/llvm/clang-format to format
  .githooks/pre-commit
  .github/workflows/ci.yaml
  Dockerfile
  hip-clang.docker
  src/include/migraphx/operation.hpp
  tools/format.py
  tools/generate.sh
Labels: enhancement, skip bot checks, Continous Integration

#1971 Update cmake to use latest and not pinned to 3.24.3
  Dockerfile
Labels: dependencies, simple, Continous Integration

#1937 Throw on calling `shape.lens()` or `shape.strides()` on a dynamic shape and vice versa
  src/common.cpp
  src/include/migraphx/op/multibroadcast.hpp
  src/include/migraphx/shape.hpp
  src/onnx/parse_instancenorm.cpp
  src/shape.cpp
  test/shape_test.cpp
  test/verify/run_verify.cpp
Labels: enhancement

#1923 Parse dynamic ONNX `Shape` op and create `dimensions_of` MIGX operator
  src/CMakeLists.txt
  src/include/migraphx/op/dimensions_of.hpp
  src/include/migraphx/operators.hpp
  src/onnx/parse_shape.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/selu_test.onnx
  test/onnx/shape_dyn_test0.onnx
  test/onnx/shape_dyn_test1.onnx
  test/onnx/shape_dyn_test2.onnx
  test/onnx/shape_dyn_test3.onnx
  test/onnx/shape_end_less_start_error.onnx
  test/onnx/shape_end_oob_test.onnx
  test/onnx/shape_start_oob_test.onnx
  test/op_shape_test.cpp
  test/ref_ops_test.cpp
Labels: roadmap

#1997 gitignore: add JetBrains intermediates to ignore
  .gitignore
Labels: skip bot checks

#1993 shared_ptr: change deprecated method unique() to use_count()
  src/include/migraphx/allocation_model.hpp
  src/include/migraphx/concat_opt.hpp
  src/include/migraphx/context.hpp
  src/include/migraphx/marker.hpp
  src/include/migraphx/operation.hpp
  src/include/migraphx/pass.hpp
  src/include/migraphx/schedule_model.hpp
  src/include/migraphx/stream_model.hpp
  src/include/migraphx/target.hpp
  tools/te.py
Labels: skip bot checks

#1996 temporarily disable CK on Windows
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/target.cpp
Labels: skip bot checks

#2004 Remove rocblas_gemm_flags_pack_int8x4 in rocblas v3.0 or higher (#2002)
  src/targets/gpu/gemm_impl.cpp
Labels: bugfix

#1994 cmake: remove linking migraphx C++ library to C test application
  test/api/CMakeLists.txt
Labels: skip bot checks

#1995 rename function 'near' to 'within_abs'
  Jenkinsfile
  test/include/test.hpp
  test/jit.cpp
Labels: skip bot checks

#1992 cmake: do not copy the driver for backward compatibility on Windows
  src/driver/CMakeLists.txt
Labels: skip bot checks
