Repository ROCm/AMDMIGraphX, pull requests merged in 2023-01, with the labels that each got.

#1510 Update GH project workflow
  .github/workflows/gh_project.yaml
Labels: simple

#1501 Update python ONNX version
  test/py/onnx_backend_test.py
  tools/install_prereqs.sh
Labels: simple

#1499 Transpose slice fix
  src/simplify_algebra.cpp
  src/simplify_reshapes.cpp
  test/simplify_algebra_test.cpp
  test/simplify_reshapes_test.cpp
  test/verify/test_trans_slice.cpp
Labels: bugfix

#1527 Dynamic onnx gemm bias
  src/onnx/parse_gemm.cpp
  test/onnx/gemm_dyn_bias_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
Labels: enhancement

#1520 Create the shape correctly in python printout
  src/module.cpp
Labels: simple, skip bot checks

#1539 Update onnxrt action
  .github/workflows/sync-onnxrt-main.yaml
Labels: skip bot checks

#1545 Update onnxrt action
  .github/workflows/sync-onnxrt-main.yaml
Labels: skip bot checks

#1531 hipRTC fixes
  Jenkinsfile
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_hip.cpp
  src/targets/gpu/compile_hip_code_object.cpp
  src/targets/gpu/device/include/migraphx/gpu/device/reduce.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/array.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/dpp.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/gathernd.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/hip.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/math.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/shape.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/types.hpp
  test/CMakeLists.txt
  test/api/test_save_load.cpp
  test/gpu/jit.cpp
Labels: enhancement, bugfix
