Repository ROCm/AMDMIGraphX, pull requests merged in 2023-11, with the labels that each got.

#2392 resolve unit test failures on navi hardware
  requirements.txt
Labels: bugfix, dependencies

#2003 Multinomial parse
  src/include/migraphx/op/multinomial.hpp
  src/include/migraphx/op/prefix_scan_op.hpp
  src/include/migraphx/op/random_uniform.hpp
  src/onnx/parse_clip.cpp
  src/onnx/parse_multinomial.cpp
  test/onnx/gen_onnx.py
  test/onnx/multinomial_autoseed_dyn_test.onnx
  test/onnx/multinomial_dyn_test.onnx
  test/onnx/multinomial_int64_test.onnx
  test/onnx/multinomial_test.onnx
  test/onnx/onnx_test.cpp
  test/onnx/verify_onnx.cpp
  test/op_shape_test.cpp
  test/ref/multinomial.cpp
Labels: onnx, Onnx Operators

#2385 suppress warnings while compiling tests on Windows
  test/api/CMakeLists.txt
Labels: Windows

#2403 Disable python tests for Python 3.6 temporarily
  test/py/CMakeLists.txt
  test/py/requirements-onnx.txt
  test/py/requirements.txt
Labels: simple, Continous Integration

#2328 fix quotation marks in CMake to accommodate Windows
  src/driver/main.cpp
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_hip.cpp
  src/version.h.in
Labels: skip bot checks, Windows

#2289 Add support for IsInf ONNX operator
  src/CMakeLists.txt
  src/include/migraphx/op/isinf.hpp
  src/onnx/parse_isinf.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/math.hpp
  test/onnx/gen_onnx.py
  test/onnx/isinf_double_pos_test.onnx
  test/onnx/isinf_half_neg_test.onnx
  test/onnx/isinf_half_pos_test.onnx
  test/onnx/isinf_half_test.onnx
  test/onnx/isinf_neg_test.onnx
  test/onnx/isinf_no_detect_test.onnx
  test/onnx/onnx_test.cpp
  test/onnx/verify_onnx.cpp
  test/py/onnx_backend_test.py
  test/ref/isinf.cpp
  test/verify/test_isinf.cpp
  test/verify/test_isinf_broadcast.cpp
Labels: onnx

#2377 Echo driver command
  src/driver/main.cpp
Labels: simple

#2306 Parse slice default steps fix
  src/onnx/parse_slice.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/reshape_variable_input_test0.onnx
  test/onnx/reshape_variable_input_test1.onnx
  test/onnx/slice_var_input_default_steps.onnx
  test/ref/reshape.cpp
Labels: bugfix, simple

#2244 Fix Round operator inaccuracy
  src/CMakeLists.txt
  src/include/migraphx/op/nearbyint.hpp
  src/include/migraphx/op/quantizelinear.hpp
  src/include/migraphx/operators.hpp
  src/onnx/parse_generic_op.cpp
  src/rewrite_quantization.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/math.hpp
  test/gpu/codegen_literal.cpp
  test/onnx/gen_onnx.py
  test/onnx/onnx_test.cpp
  test/onnx/round_half_test.onnx
  test/onnx/verify_onnx.cpp
  test/py/onnx_backend_test.py
  test/ref/nearbyint.cpp
  test/ref/quantizelinear.cpp
  test/simplify_reshapes_test.cpp
  test/verify/test_nearbyint.cpp
Labels: onnx

#2414 Port test_gpu.py to not use numpy and re-enable Python tests for Python 3.6
  test/py/CMakeLists.txt
  test/py/requirements.txt
  test/py/test_gpu.py
Labels: high priority, dependencies, Continous Integration, SLES

#2416 Fix sphinx documentation
  docs/contributor_guide.rst
  docs/dev/dev_intro.rst
  docs/driver.rst
  docs/driver/compile.rst
  docs/driver/read.rst
  docs/reference/py.rst
Labels: documentation, skip bot checks

#2423 Update README.md for GPU_TARGETS
  README.md
Labels: documentation, simple, skip bot checks

#2424 fix get_version() reporting MIGRAPH_VERSION_TWEAK
  src/driver/main.cpp
Labels: Windows

#2394 Handle all slice input variations
  src/include/migraphx/op/normalize_attribute.hpp
  src/include/migraphx/op/slice.hpp
  src/normalize_attributes.cpp
  src/onnx/parse_slice.cpp
  test/op_shape_test.cpp
  test/ref/slice.cpp
Labels: onnx

#2425 fix call to std::isinf() on Windows
  src/include/migraphx/op/isinf.hpp
Labels: Windows

#2426 fix missing exports on Windows
  src/include/migraphx/module.hpp
Labels: Windows

#2417 Environment variable documentation
  docs/contributor_guide.rst
  docs/dev/env_vars.rst
Labels: documentation, skip bot checks

#2440 add missing <array> header file
  src/include/migraphx/op/slice.hpp
Labels: Windows

#2319 Remove contiguous from passes for reshapes
  src/fuse_pointwise.cpp
  src/simplify_algebra.cpp
  src/simplify_reshapes.cpp
  test/fuse_pointwise.cpp
  test/simplify_algebra_test.cpp
  test/simplify_reshapes_test.cpp
Labels: Cleanup

#2390 Support per-axis quantization
  src/include/migraphx/matcher.hpp
  src/simplify_qdq.cpp
  test/quantization.cpp
  test/simplify_qdq_test.cpp
Labels: enhancement, TorchMIGraphX

#2401 fix detection of hiprtc driver on Windows
  src/dynamic_loader.cpp
  src/include/migraphx/dynamic_loader.hpp
  src/targets/gpu/compile_hip.cpp
Labels: skip bot checks, Windows

#2438 Ref implementation of FP8
  src/api/include/migraphx/migraphx.h
  src/include/migraphx/bit_cast.hpp
  src/include/migraphx/float8.hpp
  src/include/migraphx/float8_impl.hpp
  src/include/migraphx/half.hpp
  src/include/migraphx/shape.hpp
  src/include/migraphx/type_traits.hpp
  src/py/migraphx_py.cpp
  src/targets/gpu/device/include/migraphx/gpu/device/types.hpp
  src/targets/gpu/gemm_impl.cpp
  test/CMakeLists.txt
  test/float_equal.cpp
  test/fp8e4m3fn.cpp
  test/fp8e4m3fnuz.cpp
  test/fp8e5m2.cpp
  test/fp8e5m2fnuz.cpp
  test/gpu/jit.cpp
  tools/api/migraphx.h
Labels: high priority

#2402 enable compilation on Windows
  .gitignore
  CMakeLists.txt
  src/CMakeLists.txt
  src/driver/argument_parser.hpp
  src/onnx/CMakeLists.txt
  src/register_target.cpp
  src/targets/cpu/CMakeLists.txt
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/prefuse_ops.cpp
  src/targets/ref/CMakeLists.txt
  src/tf/CMakeLists.txt
  src/tmp_dir.cpp
  test/jit.cpp
Labels: Windows

#2330 embed.cmake: add support for Windows resource file
  cmake/Embed.cmake
  src/targets/gpu/CMakeLists.txt
Labels: Windows

#2464 add missing <array> header file
  test/include/test.hpp
Labels: Windows

#2445 Simplify constant variable input slices
  src/simplify_dyn_ops.cpp
  test/simplify_dyn_ops_test.cpp
Labels: enhancement

#2165 Use parallel STL for parallel execution
  Jenkinsfile
  src/CMakeLists.txt
  src/include/migraphx/op/binary.hpp
  src/include/migraphx/op/unary.hpp
  src/include/migraphx/par.hpp
  src/include/migraphx/par_for.hpp
  src/include/migraphx/simple_par_for.hpp
  src/schedule.cpp
  tools/install_prereqs.sh
Labels: enhancement, dependencies

#2470 suppress warning about missing TBB package
  src/CMakeLists.txt
Labels: Windows

#2477 Use size_t to fix hiprtc compile errors
  src/targets/gpu/kernels/include/migraphx/kernels/gathernd.hpp
  test/gpu/jit.cpp
Labels: bugfix

#2483 Add find_dependency for TBB
  src/CMakeLists.txt
Labels: bugfix, high priority

#2496 Have the accuracy checker print the whole final buffer
  tools/accuracy/accuracy_checker.py
Labels: simple, skip bot checks
