Repository ROCm/AMDMIGraphX, pull requests merged in 2023-04, with the labels that each got.

#1634 Enable header tests for FPGA and CPU backend
  src/targets/cpu/include/migraphx/cpu/parallel.hpp
  src/targets/ref/CMakeLists.txt
  test/CMakeLists.txt
Labels: skip performance check

#1594 fix stable diffusion decoder non standard shape issue
  src/include/migraphx/op/contiguous.hpp
  src/onnx/parse_reshape.cpp
  test/onnx/onnx_test.cpp
  test/op_shape_test.cpp
  test/shape_test.cpp
Labels: bugfix

#1660 fix bug in transpose_slice simplification
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: bugfix

#1614 Add reduction fusion
  src/CMakeLists.txt
  src/cpp_generator.cpp
  src/fuse_reduce.cpp
  src/include/migraphx/cpp_generator.hpp
  src/include/migraphx/fuse_reduce.hpp
  src/include/migraphx/module.hpp
  src/include/migraphx/op/reduce_op.hpp
  src/module.cpp
  src/targets/gpu/compile_gen.cpp
  src/targets/gpu/include/migraphx/gpu/compile_gen.hpp
  src/targets/gpu/include/migraphx/gpu/compile_hip_code_object.hpp
  src/targets/gpu/jit/reduce.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/functional.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/index.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/reduce.hpp
  src/targets/gpu/target.cpp
  test/fuse_reduce.cpp
  test/include/pointwise.hpp
Labels: enhancement, high priority

#1658 Enable hiprtc by default
  rbuild.ini
  src/targets/gpu/CMakeLists.txt
  tools/build_and_test_onnxrt.sh
Labels: high priority

#1669 Fix 2 input broadcast bug for dynamic batch and output parameter ordering
  src/include/migraphx/matcher.hpp
  src/include/migraphx/op/select_module.hpp
  src/split_single_dyn_dim.cpp
  test/split_single_dyn_dim_test.cpp
Labels: bugfix, high priority

#1667 Print out pass name when tracing passes
  src/pass_manager.cpp
Labels: simple

#1587 Make JIT and pointwise work with zero input args
  src/cpp_generator.cpp
  src/fuse_pointwise.cpp
  src/include/migraphx/op/pointwise.hpp
  test/fuse_pointwise.cpp
  test/op_shape_test.cpp
Labels: bugfix

#1686 Add trace flag for propagate_constant
  src/propagate_constant.cpp
Labels: enhancement, simple

#1691 Use hash key for docker layer computed from Dockerfile
  .github/workflows/ci.yaml
  .github/workflows/clean-closed-pr-caches.yaml
Labels: skip bot checks

#1696 Expose instruction shape and operator through python api
  src/py/migraphx_py.cpp
  test/py/test_instruction.py
Labels: simple

#1690 Update multi() to work with non-std shapes
  src/include/migraphx/shape.hpp
  src/shape.cpp
  test/shape_test.cpp
Labels: simple

#1702 Fix compile failure in reduction fusion of instance norm
  src/cpp_generator.cpp
  src/include/migraphx/cpp_generator.hpp
  src/targets/gpu/compile_gen.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/reduce.hpp
  test/verify/test_reduce_mean_bias_half.cpp
Labels: bugfix

#1694 Dynamic shape hip::copy_to_gpu and hip::copy_from_gpu
  src/include/migraphx/op/select_module.hpp
  src/targets/gpu/device/include/migraphx/gpu/device/visit.hpp
  src/targets/gpu/include/migraphx/gpu/hip.hpp
Labels: simple

#1716 update rocBLAS version check to support 3.0 and above
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/rocblas.cpp
Labels: bugfix, simple

#1717 Adding readme for workflows
  .github/workflows/README.md
Labels: skip bot checks

#1725 Rename parameter for fuse CK to use _0 instead of .0
  src/targets/gpu/fuse_ck.cpp
Labels: bugfix

#1711 Removed split_single_dyn_dim compile flag
  doc/src/driver/compile.rst
  examples/migraphx/migraphx_driver/README.md
  src/driver/main.cpp
  src/include/migraphx/compile_options.hpp
  src/split_single_dyn_dim.cpp
  src/targets/gpu/target.cpp
  test/verify/test_split_single_dyn_dim.cpp
Labels: high priority, simple
