Repository ROCm/AMDMIGraphX, pull requests merged in 2023-12, with the labels that each got.

#2442 Add a tuning limit for mlir
  docs/dev/env_vars.rst
  src/targets/gpu/mlir.cpp
Labels: bugfix

#2509 Remove unused device kernels
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/device/gather.cpp
  src/targets/gpu/device/pad.cpp
  src/targets/gpu/gather.cpp
  src/targets/gpu/include/migraphx/gpu/device/gather.hpp
  src/targets/gpu/include/migraphx/gpu/device/pad.hpp
  src/targets/gpu/include/migraphx/gpu/gather.hpp
  src/targets/gpu/include/migraphx/gpu/pad.hpp
  src/targets/gpu/pad.cpp
Labels: simple, skip bot checks, Cleanup

#2473 Add FP8 rocblas gemm support
  src/eliminate_data_type.cpp
  src/include/migraphx/eliminate_data_type.hpp
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/rocblas.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/float8.hpp
  src/targets/gpu/rocblas.cpp
  src/targets/gpu/target.cpp
  test/verify/gemm_2args_bmv.cpp
  test/verify/gemm_2args_mm_1.cpp
  test/verify/gemm_2args_mm_2.cpp
  test/verify/gemm_2args_mm_3.cpp
  test/verify/gemm_2args_mm_4.cpp
  test/verify/gemm_2args_mm_5.cpp
  test/verify/gemm_2args_mm_6.cpp
  test/verify/gemm_2args_mm_7.cpp
  test/verify/gemm_2args_mm_8.cpp
  test/verify/gemm_2args_mv.cpp
  test/verify/gemm_2args_vbm.cpp
  test/verify/gemm_2args_vm.cpp
  test/verify/gemm_2args_vv.cpp
  test/verify/gemm_add.cpp
  test/verify/gemm_add_broadcast1.cpp
  test/verify/gemm_add_broadcast2.cpp
  test/verify/gemm_add_broadcast_half.cpp
  test/verify/gemm_add_half.cpp
  test/verify/gemm_literal.cpp
  test/verify/gemm_multi_3args.cpp
  test/verify/gemm_multi_3args_alpha0.cpp
  test/verify/gemm_multi_3args_beta0.cpp
  test/verify/gemm_multi_3args_c25.cpp
  test/verify/gemm_multi_dim_2.cpp
  test/verify/gemm_multi_dim_2_3.cpp
  test/verify/gemm_multi_transpose.cpp
  test/verify/test_convert.cpp
  test/verify/test_gemm.cpp
  test/verify/test_gemm_copy.cpp
  test/verify/test_gemm_ex.cpp
  test/verify/test_gemm_half.cpp
  test/verify/test_gemm_transposea.cpp
  test/verify/test_gemm_transposea_ex.cpp
  test/verify/test_gemm_transposeab.cpp
  test/verify/test_gemm_transposeb.cpp
  test/verify/test_gemm_transposeb_ex.cpp
  test/verify/test_mul_dot_a.cpp
  test/verify/test_mul_dot_b.cpp
  test/verify/test_unbatched_gemm_1.cpp
  test/verify/test_unbatched_gemm_2.cpp
Labels: FP8

#2510 Device kernels using FP8
  src/targets/gpu/target.cpp
  test/verify/gemm_2args_mm_8.cpp
  test/verify/gemm_add_broadcast2.cpp
  test/verify/test_arg_ops.cpp
  test/verify/test_contiguous.cpp
  test/verify/test_logsoftmax.cpp
  test/verify/test_multinomial.cpp
  test/verify/test_nonzero.cpp
  test/verify/test_nonzero_half.cpp
  test/verify/test_prefix_scan_sum_2d.cpp
  test/verify/test_reverse.cpp
  test/verify/test_rnn_sql_1.cpp
  test/verify/test_scatter0.cpp
  test/verify/test_topk_0.cpp
Labels: FP8

#2531 Add warnings for FP8 onnx
  src/onnx/onnx_parser.cpp
Labels: simple, skip bot checks, FP8

#2528 Enable simplify qdq to work with FP8 types and fix bug in pass
  src/include/migraphx/op/dequantizelinear.hpp
  src/include/migraphx/op/quantizelinear.hpp
  src/rewrite_quantization.cpp
  src/simplify_qdq.cpp
  test/simplify_qdq_test.cpp
Labels: FP8

#2530 Print Ref compiled program in verify tests
  test/verify/run_verify.cpp
  test/verify/run_verify.hpp
Labels: simple, skip bot checks

#2532 Add Fp8 warnings in finalize
  src/module.cpp
Labels: simple, skip bot checks, FP8

#2535 Add `--fp8` option to quantize models in FP8 inside `migraphx-driver`
  docs/dev/env_vars.rst
  docs/driver/compile.rst
  examples/migraphx/migraphx_driver/README.md
  src/CMakeLists.txt
  src/driver/main.cpp
  src/include/migraphx/quantization.hpp
  src/include/migraphx/quantize_8bits.hpp
  src/quantization.cpp
  src/quantize_8bits.cpp
  src/simplify_qdq.cpp
  test/quantization.cpp
Labels: FP8

#2544 refactoring quantization passes
  src/api/api.cpp
  src/include/migraphx/quantization.hpp
  src/include/migraphx/quantize_8bits.hpp
  src/py/migraphx_py.cpp
  src/quantization.cpp
  src/quantize_8bits.cpp
  test/quantization.cpp
  tools/api/api.cpp
Labels: simple

#2508 Make reshape copy always have standard shape as output
  src/include/migraphx/op/reshape.hpp
  test/op_shape_test.cpp
Labels: bugfix, Cleanup

#2505 Lazy reshape fixes
  src/include/migraphx/functional.hpp
  src/include/migraphx/op/reshape_lazy.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/functional.hpp
  test/op_shape_test.cpp
Labels: bugfix

#2549 Allow reshape ops between dq and quant_op
  src/include/migraphx/matcher.hpp
  src/simplify_qdq.cpp
  test/simplify_qdq_test.cpp
Labels: roadmap, TorchMIGraphX

#2548 Fix compilation of math functions on Windows
  src/simplify_qdq.cpp
Labels: Windows

#2553 Fixed iterator_out_of_range error in test_op_shape
  src/include/migraphx/op/scatternd_op.hpp
Labels: Windows

#2554 Change ccache location in CI servers
  Jenkinsfile
Labels: bugfix

#2563 Removal of e-Tugra root certificate
  docs/.sphinx/requirements.txt
Labels: dependencies

#2472 Standardize documentation and add Conda configuration for ReadtheDocs
  .dockerignore
  .github/dependabot.yml
  .gitignore
  .readthedocs.yaml
  Dockerfile
  README.md
  docs/.sphinx/requirements.in
  docs/conf.py
  docs/doxygen/Doxyfile
  docs/environment.yml
  docs/license.md
  docs/sphinx/_toc.yml.in
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
  hip-clang.docker
  tools/docker/sles.docker
  tools/docker/ubuntu_2204.dockerfile
Labels: documentation

#2574 fix test ref scatternd_op.hpp brackets
  src/include/migraphx/op/scatternd_op.hpp
Labels: bugfix, Cleanup

#1651 Threaded ref nms
  CMakeLists.txt
  src/include/migraphx/op/nonmaxsuppression.hpp
Labels: enhancement, roadmap

#2408 Fix bug in pad operator from dimension reduction
  src/targets/gpu/jit/pad.cpp
  test/verify/test_pad_asymmetrical.cpp
Labels: bugfix

#2575 doc: fix note style for github markdown
  README.md
Labels: documentation, skip bot checks

#2576 doc: fix highlight for cmake codeblock
  README.md
Labels: documentation, skip bot checks
