Repository ROCm/AMDMIGraphX, pull requests merged in 2024-05, with the labels that each got.

#3028 CI ONNX set minimum to 1.14.1
  test/py/requirements-onnx.txt
Labels: bugfix

#3026 Dot outer dimensions check revert
  src/include/migraphx/op/dot.hpp
  test/op_shape_test.cpp
Labels: bugfix, dependencies

#3027 Fix expand parsing
  src/onnx/parse_expand.cpp
  test/onnx/expand_dyn_input_dyn_output_test.onnx
  test/onnx/expand_dyn_input_static_dims_throw.onnx
  test/onnx/expand_dyn_test.onnx
  test/onnx/expand_static_input_dyn_output_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/expand_test.cpp
Labels: bugfix, simple

#3047 Fix problem with slow performance with reduction fusion
  src/targets/gpu/compile_gen.cpp
Labels: simple, Perf Improve

#3048 Improve scalar fusions when not all strides are 0
  src/fuse_pointwise.cpp
  test/fuse_pointwise.cpp
Labels: simple, Perf Improve

#2973 Add support for MaxPool unit8 type
  src/targets/gpu/target.cpp
  test/py/onnx_backend_test.py
  test/verify/test_global_max_pooling.cpp
  test/verify/test_max_pooling_ceil_3d.cpp
Labels: bugfix, Onnx Operators

#3065 print uint8 and int8 numbers
  src/include/migraphx/as_number.hpp
  src/include/migraphx/stringutils.hpp
  src/include/migraphx/tensor_view.hpp
Labels: simple

#3042 Bump rocMLIR SHA
  requirements.txt
Labels: dependencies

#2966 Remove rocblas on windows
  CMakeLists.txt
  src/CMakeLists.txt
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_miopen.cpp
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/fuse_ops.cpp
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/compile_miopen.hpp
  src/targets/gpu/include/migraphx/gpu/context.hpp
  src/targets/gpu/include/migraphx/gpu/gemm.hpp
  src/targets/gpu/include/migraphx/gpu/rocblas.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/rocblas.cpp
  src/targets/gpu/target.cpp
  test/gpu/gemm_tune.cpp
Labels: Windows

#3035 Squeeze dyn dim allow compatible
  src/include/migraphx/op/squeeze.hpp
  test/op_shape_test.cpp
Labels: simple

#3051 Add hip stream and events to SDXL example
  examples/diffusion/python_stable_diffusion_xl/README.md
  examples/diffusion/python_stable_diffusion_xl/gradio_app.py
  examples/diffusion/python_stable_diffusion_xl/requirements.txt
  examples/diffusion/python_stable_diffusion_xl/txt2img.py
Labels: skip bot checks

#3022 Add logic to unfuse mlir and pointwise module for the split-k GEMM configs
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/include/migraphx/gpu/mlir.hpp
  src/targets/gpu/jit/mlir.cpp
  src/targets/gpu/mlir.cpp
  test/gpu/mlir.cpp
  test/verify/test_gemm.cpp
Labels: bugfix

#3036 Sort parameter inputs into `select_module` from `split_single_dyn_dim` pass
  src/split_single_dyn_dim.cpp
  test/split_single_dyn_dim_test.cpp
Labels: simple

#3070 Fix bug in finding parallel reductions
  src/targets/cpu/lowering.cpp
  src/targets/gpu/prepare_reduce.cpp
  test/verify/test_reduce_mean_reduce_sum.cpp
Labels: bugfix

#3074 Fix missing/dud parse tests
  test/onnx/mvn_default_axes_rank_too_big_test.onnx
  test/onnx/parse/batch_norm_invalid_bias_rank.cpp
  test/onnx/parse/batch_norm_invalid_rank.cpp
  test/onnx/parse/convinteger_bad_data_bias_type.cpp
  test/onnx/parse/convinteger_bad_weight_bias_type.cpp
  test/onnx/parse/matmulinteger_zp_mismatch_error_test.cpp
Labels: simple, skip bot checks

#3069 Fix bug in computing dominator
  src/dom_info.cpp
  test/dom.cpp
Labels: bugfix

#3083 Fix "All Targets" CI test
  test/multi_target/multitarget_test.cpp
Labels: skip bot checks

#3084 Enable MIOpen and CK fusion on gfx941 and gfx942
  src/targets/gpu/fuse_ck.cpp
  src/targets/gpu/fuse_ops.cpp
Labels: simple

#3082 Fix `is_module_fusible()` bug in MIGraphX
  src/instruction.cpp
  src/targets/gpu/include/migraphx/gpu/mlir.hpp
  src/targets/gpu/jit/mlir.cpp
  src/targets/gpu/mlir.cpp
  test/verify/gemm_add.cpp
  test/verify/test_gemm.cpp
Labels: bugfix, simple

#3067 find_split_concat fix
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: bugfix, simple, Matchers, TorchMIGraphX

#3054 Improve handling for adding more than 10 parameters to a submodule
  CMakeLists.txt
  src/fuse_pointwise.cpp
  src/include/migraphx/param_utils.hpp
  src/param_utils.cpp
  src/targets/gpu/fuse_mlir.cpp
  test/param_utils.cpp
Labels: bugfix, Cleanup

#3038 dimensions match in find_pointwise_reduce
  src/fuse_reduce.cpp
  src/include/migraphx/matcher.hpp
  src/program.cpp
  test/fuse_reduce.cpp
Labels: TorchMIGraphX

#3099 Fuse reduce when broadcast is after reshape
  src/include/migraphx/rewrite_reshapes.hpp
  test/fuse_reduce.cpp
Labels: Continous Integration, Cleanup

#3090 Add TF tests to the test package
  src/include/migraphx/tf.hpp
  src/tf/tf.cpp
  src/tf/tf_parser.cpp
  test/CMakeLists.txt
  test/tf/CMakeLists.txt
  test/tf/tf_test.cpp
Labels: skip bot checks

#3096 Concat - multibroadcast fix
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: bugfix, TorchMIGraphX

#3114 Ci improvements
  .github/workflows/config.md
  .github/workflows/performance.yaml
  .github/workflows/sync_rocMLIR.yaml
  .github/workflows/weekly_master_sync.yaml
Labels: skip bot checks

#3108 MIGraphx private lib changes
  dev-requirements.txt
  src/CMakeLists.txt
  src/targets/cpu/CMakeLists.txt
  src/targets/fpga/CMakeLists.txt
  src/targets/gpu/CMakeLists.txt
  src/targets/ref/CMakeLists.txt
  src/tf/CMakeLists.txt
Labels: enhancement

#3116 added set_bypass() call
  src/fuse_reduce.cpp
  test/fuse_reduce.cpp
Labels: bugfix, TorchMIGraphX

#3111 Fix hipExtModuleLaunchKernel function
  src/targets/gpu/kernel.cpp
Labels: bugfix, Windows, UAI

#3034 `Split` dynamic shape parsing update
  src/onnx/parse_split.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/split_dyn_input.cpp
  test/onnx/parse/split_minus_axis_test.cpp
  test/onnx/split_dyn_input_dyn_split_axis_test.onnx
  test/onnx/split_dyn_input_fixed_split_axis_test.onnx
  test/onnx/split_dyn_input_split_attr_test.onnx
  test/onnx/split_dyn_input_split_input_test.onnx
  test/onnx/verify/split_dyn_verify_test.cpp
Labels: roadmap

#2823 Prevent collapsing batch dims in dot ops with constants
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: Perf Improve
