Repository ROCm/AMDMIGraphX, pull requests merged in 2024-12, with the labels that each got.

#3668 Added onnx_operators to TOC and landing page
  docs/index.rst
  docs/sphinx/_toc.yml.in
Labels: documentation

#3667 updated metadata
  docs/dev/data.rst
  docs/dev/dev_intro.rst
  docs/dev/env_vars.rst
  docs/dev/matchers.rst
  docs/dev/onnx_operators.rst
  docs/dev/operators.rst
  docs/dev/pass.rst
  docs/dev/program.rst
  docs/dev/quantization.rst
  docs/dev/targets.rst
  docs/dev/tools.rst
  docs/dev/triage-rocmlir.rst
  docs/reference/cpp.rst
  docs/reference/driver-options.rst
  docs/reference/py.rst
Labels: documentation

#3657 Refactor GPU math functions
  src/targets/gpu/kernels/include/migraphx/kernels/functional.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/math.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/pp.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/type_traits.hpp
  test/gpu/jit.cpp
Labels: Cleanup, Perf Improve

#3610 Track broadcast axes in the shape_transform_descriptor
  src/include/migraphx/shape_transform_descriptor.hpp
  src/shape_transform_descriptor.cpp
  test/shape_transform_descriptor.cpp
  test/simplify_reshapes_test.cpp
Labels: enhancement

#3655 bit_cast operator
  src/CMakeLists.txt
  src/include/migraphx/op/bit_cast.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/bit_cast.hpp
  test/op_shape_test.cpp
  test/ref/bit_cast.cpp
  test/verify/main.cpp
  test/verify/test_bit_cast.cpp
Labels: roadmap, FP8

#3662 GEMM pointwise fusion for hipBLASLt
  src/targets/gpu/fuse_ops.cpp
  test/gpu/fuse_gemm.cpp
Labels: enhancement

#3672 Print python from onxx backend test
  src/py/backend/backend.py
  src/py/migraphx_py.cpp
Labels: simple, Continous Integration

#3541 Enable non-packed inputs for mlir
  src/targets/gpu/fuse_mlir.cpp
Labels: enhancement, rocMLIR

#3683 normalize standard input shapes to blas gemms
  src/targets/gpu/fuse_ops.cpp
  src/targets/gpu/gemm_impl.cpp
  test/verify/test_gemm_add_broadcast3.cpp
Labels: bugfix

#3696 Disable fp8e5m2fnuz on rocBLAS
  src/targets/gpu/target.cpp
Labels: simple

#3698 MatMulNBits collapse shape input when > 1d
  src/onnx/parse_matmulnbits.cpp
Labels: bugfix

#3701 catch python buffer unsupported types
  src/py/migraphx_py.cpp
Labels: bugfix

#3703 Updates to CHANGELOG for 6.3
  CHANGELOG.md
Labels: roadmap, documentation

#3709 Enable split reduce by default
  docs/dev/env_vars.rst
  src/fuse_pointwise_reduce.cpp
  src/include/migraphx/fuse_pointwise_reduce.hpp
  src/split_reduce.cpp
  src/targets/gpu/target.cpp
  test/split_reduce.cpp
Labels: enhancement, roadmap, simple

#3712 Normalize standard input shapes to hipBLASLt gemms
  src/targets/gpu/fuse_ops.cpp
  src/targets/gpu/hip_gemm_impl.cpp
Labels: bugfix, simple

#3706 Add changes for contiguous transpose gemm fusion for hipblaslt
  src/targets/gpu/fuse_ops.cpp
  src/targets/gpu/hip_gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/hip_gemm.hpp
Labels: enhancement, Perf Improve

#3702 Do not run hip gemm pointwise fusion for quant_dot
  src/targets/gpu/fuse_ops.cpp
Labels: bugfix

#3630 Bf16 gpu support
  src/driver/main.cpp
  src/driver/precision.hpp
  src/driver/verify.cpp
  src/include/migraphx/quantization.hpp
  src/py/migraphx_py.cpp
  src/quantization.cpp
  src/targets/gpu/device/include/migraphx/gpu/device/float_equal.hpp
  src/targets/gpu/device/include/migraphx/gpu/device/types.hpp
  src/targets/gpu/device/include/migraphx/gpu/device/visit.hpp
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/miopen.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/types.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/mlir.cpp
  src/targets/gpu/target.cpp
Labels: enhancement, roadmap, bf16

#3714 Remove __AMDGCN_WAVEFRONT_SIZE for deprecation
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_hip_code_object.cpp
  src/targets/gpu/include/migraphx/gpu/compile_hip_code_object.hpp
  src/targets/gpu/jit/ck_gemm.cpp
  src/targets/gpu/jit/ck_gemm_softmax_gemm.cpp
  src/targets/gpu/jit/compute_attention_probabilities.cpp
  src/targets/gpu/jit/compute_attention_scores.cpp
  src/targets/gpu/jit/concat.cpp
  src/targets/gpu/jit/concat_past_present.cpp
  src/targets/gpu/jit/gather.cpp
  src/targets/gpu/jit/gathernd.cpp
  src/targets/gpu/jit/gqa_rotary_embedding.cpp
  src/targets/gpu/jit/gqa_softmax.cpp
  src/targets/gpu/jit/layernorm.cpp
  src/targets/gpu/jit/pad.cpp
  src/targets/gpu/jit/pointwise.cpp
  src/targets/gpu/jit/pooling.cpp
  src/targets/gpu/jit/reduce.cpp
  src/targets/gpu/jit/roialign.cpp
  src/targets/gpu/jit/scatter.hpp
  src/targets/gpu/jit/softmax.cpp
  src/targets/gpu/jit/unpack_int4.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/index.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/reduce.hpp
  test/gpu/jit.cpp
Labels: roadmap, Cleanup

#3445 Parser changes to handle MatMulIntegerToFloat
  src/onnx/parse_matmul.cpp
  test/onnx/gen_onnx.py
  test/onnx/matmulintegertofloat_bad_bias_test.onnx
  test/onnx/matmulintegertofloat_bad_bias_test2.onnx
  test/onnx/matmulintegertofloat_bad_bias_test3.onnx
  test/onnx/matmulintegertofloat_bad_scale2_test.onnx
  test/onnx/matmulintegertofloat_bad_scale3_test.onnx
  test/onnx/matmulintegertofloat_bad_scale4_test.onnx
  test/onnx/matmulintegertofloat_bad_scale5_test.onnx
  test/onnx/matmulintegertofloat_bad_scale_test.onnx
  test/onnx/matmulintegertofloat_half_test.onnx
  test/onnx/matmulintegertofloat_half_zp_bias_test.onnx
  test/onnx/matmulintegertofloat_half_zp_test.onnx
  test/onnx/matmulintegertofloat_scalar_scale_test.onnx
  test/onnx/matmulintegertofloat_scalar_zp_test.onnx
  test/onnx/matmulintegertofloat_test.onnx
  test/onnx/matmulintegertofloat_zp_bias_3d_test.onnx
  test/onnx/matmulintegertofloat_zp_bias_test.onnx
  test/onnx/matmulintegertofloat_zp_test.onnx
  test/onnx/parse/matmulintegerToFloat_bad_bias_test.cpp
  test/onnx/parse/matmulintegerToFloat_bad_bias_test2.cpp
  test/onnx/parse/matmulintegerToFloat_bad_bias_test3.cpp
  test/onnx/parse/matmulintegerToFloat_bad_scale2_test.cpp
  test/onnx/parse/matmulintegerToFloat_bad_scale3_test.cpp
  test/onnx/parse/matmulintegerToFloat_bad_scale4_test.cpp
  test/onnx/parse/matmulintegerToFloat_bad_scale5_test.cpp
  test/onnx/parse/matmulintegerToFloat_bad_scale_test.cpp
  test/onnx/parse/matmulinteger_dual_zp_test.cpp
  test/onnx/parse/matmulinteger_one_zp_test.cpp
  test/onnx/parse/matmulintegertofloat_half_test.cpp
  test/onnx/parse/matmulintegertofloat_half_zp_test.cpp
  test/onnx/parse/matmulintegertofloat_scalar_scale_test.cpp
  test/onnx/parse/matmulintegertofloat_scalar_zp_test.cpp
  test/onnx/parse/matmulintegertofloat_test.cpp
  test/onnx/parse/matmulintegertofloat_zp_bias_test.cpp
  test/onnx/parse/matmulintegertofloat_zp_test.cpp
  test/onnx/verify/matmulintegertofloat_int8_uint8_scales_zp_bias.cpp
  test/onnx/verify/matmulintegertofloat_int8_uint8_scales_zp_bias_3d.cpp
Labels: onnxruntime, Onnx Operators, UAI

#3720 Use native fp16 type
  src/targets/gpu/kernels/include/migraphx/kernels/math.hpp
  test/gpu/jit.cpp
Labels: bugfix

#3705 Fuse transposes in pointwise and reduce fusions
  src/include/migraphx/rewrite_reshapes.hpp
  src/include/migraphx/shape_transform_descriptor.hpp
  src/shape_transform_descriptor.cpp
  test/fuse_pointwise.cpp
  test/fuse_reduce.cpp
  test/shape_transform_descriptor.cpp
  tools/cppcheck/migraphx.py
Labels: enhancement, Perf Improve

#3717 Netron output (ONNX JSON)
  codecov.yml
  requirements.txt
  src/CMakeLists.txt
  src/base64.cpp
  src/driver/main.cpp
  src/include/migraphx/base64.hpp
  src/include/migraphx/netron_output.hpp
  src/netron_output.cpp
  test/base64_test.cpp
Labels: enhancement, roadmap
