Repository ROCm/AMDMIGraphX, pull requests merged in 2024-09, with the labels that each got.

#3407 fix bug in exhaustive-tune
  requirements.txt
Labels: bugfix

#3426 docs/6.2.0: fix sidebar title (#3366)
  docs/conf.py
Labels: documentation

#3313 rnnt_example_start
  examples/nlp/python_rnnt/README.md
  examples/nlp/python_rnnt/download_helper_files.sh
  examples/nlp/python_rnnt/requirements.txt
  examples/nlp/python_rnnt/rnnt.py
  examples/nlp/python_rnnt/rnnt_data.py
  examples/nlp/python_rnnt/rnnt_onnx.py
  examples/nlp/python_rnnt/rnnt_torch_model.py
Labels: onnx, Example Model, PyTorch

#3413 Add onnx files for softmaxcrossentropyloss tests
  test/onnx/softmaxcrossentropyloss_2d_mean_reduction_double_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_mean_reduction_double_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_mean_reduction_half_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_mean_reduction_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_mean_reduction_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_asym_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_double_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_double_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_half_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_half_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_asym_class_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_asym_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_ignore_idx_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_neg_ignore_idx_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_neg_out_bounds_ignore_idx_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_out_bounds_ignore_idx_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_sum_reduction_double_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_sum_reduction_double_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_sum_reduction_half_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_sum_reduction_half_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_sum_reduction_test.onnx
  test/onnx/softmaxcrossentropyloss_2d_sum_reduction_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_invalid_reduction_test.onnx
  test/onnx/softmaxcrossentropyloss_kd_mean_reduction_half_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_kd_no_reduction_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_kd_sum_reduction_double_weighted_test.onnx
  test/onnx/softmaxcrossentropyloss_label_wrong_type_test.onnx
  test/onnx/softmaxcrossentropyloss_score_dim_err_test.onnx
  test/onnx/softmaxcrossentropyloss_score_label_mismatch_test.onnx
  test/onnx/softmaxcrossentropyloss_score_label_wrong_k_dims_test.onnx
  test/onnx/softmaxcrossentropyloss_scores_wrong_type_test.onnx
  test/onnx/softmaxcrossentropyloss_weight_score_mismatch_valid_type_test.onnx
  test/onnx/softmaxcrossentropyloss_weight_wrong_dims_test.onnx
  test/onnx/softmaxcrossentropyloss_weight_wrong_type_test.onnx
Labels: Continous Integration, Cleanup, Onnx Operators

#2971 Gridsample bicubic mode
  docs/dev/onnx_operators.rst
  src/onnx/parse_gridsample.cpp
  test/onnx/gen_onnx.py
  test/onnx/gridsample_bicubic_align_corners_0_additional_1_test.onnx
  test/onnx/gridsample_bicubic_align_corners_1_additional_1_test.onnx
  test/onnx/verify/gridsample_bicubic_align_corners_0_additional_1_test.cpp
  test/onnx/verify/gridsample_bicubic_align_corners_1_additional_1_test.cpp
  test/onnx/verify/gridsample_bicubic_test.cpp
  test/py/onnx_backend_test.py
Labels: Onnx Operators

#3285 adjust stride ordering rules for standard shape: stride can be anythi…
  src/auto_contiguous.cpp
  src/include/migraphx/check_shapes.hpp
  src/include/migraphx/program.hpp
  src/program.cpp
  src/shape.cpp
  src/targets/gpu/fuse_ops.cpp
  test/auto_contiguous_test.cpp
  test/shape_test.cpp
Labels: TorchMIGraphX

#3008 Add softmax cross entropy
  src/onnx/parse_softmaxcrossentropyloss.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/softmaxcrossentropy_err_test.cpp
  test/onnx/parse/softmaxcrossentropyloss_2d_mean_reduction_test.cpp
  test/onnx/parse/softmaxcrossentropyloss_2d_no_reduction_test.cpp
  test/onnx/parse/softmaxcrossentropyloss_2d_sum_reduction_test.cpp
  test/onnx/parse/softmaxcrossentropyloss_kd_all_reduction_weighted_test.cpp
  test/onnx/softmaxcrossentropyloss_2d_no_reduction_weighted_neg_ignore_idx_test2.onnx
  test/onnx/softmaxcrossentropyloss_kdim_not_equal_test.onnx
  test/onnx/verify/softmaxcrossentropyloss_kd_dim_weighted.cpp
  test/onnx/verify/softmaxcrossentropyloss_no_attr.cpp
  test/onnx/verify/softmaxcrossentropyloss_weighted.cpp
  test/py/onnx_backend_test.py
  test/verify/test_softmaxcrossentropyloss_2d.cpp
  test/verify/test_softmaxcrossentropyloss_2d_mean.cpp
  test/verify/test_softmaxcrossentropyloss_2d_sum.cpp
  test/verify/test_softmaxcrossentropyloss_kd.cpp
  test/verify/test_softmaxcrossentropyloss_kd_mean.cpp
  test/verify/test_softmaxcrossentropyloss_kd_sum.cpp
Labels: onnx, onnxruntime, high priority, Onnx Operators

#3202 Layernorm Perf improvement: increase wg size
  src/targets/gpu/jit/layernorm.cpp
Labels: Perf Improve

#3403 Generalize attention fusion
  src/include/migraphx/instruction.hpp
  src/include/migraphx/match/softmax.hpp
  src/include/migraphx/module.hpp
  src/module.cpp
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/prefuse_ops.cpp
  test/gpu/fuse_mlir.cpp
  test/module_test.cpp
Labels: enhancement

#3340 Bump ci rocm6.2
  CMakeLists.txt
  Dockerfile
  hip-clang.docker
  src/include/migraphx/layout_nhwc.hpp
  src/include/migraphx/operation.hpp
  src/include/migraphx/pass.hpp
  test/bit_signal.cpp
  tools/docker/migraphx_with_onnxruntime_pytorch.docker
  tools/docker/sles.docker
  tools/docker/ubuntu_2204.dockerfile
Labels: Continous Integration

#3466 Defaulting HIP_PLATFORM to `amd` on Windows
  src/targets/gpu/CMakeLists.txt
Labels: Windows, UAI

#3469 Make hipcc part of install prereqs and cleanup commented line
  hip-clang.docker
  tools/docker/sles.docker
  tools/install_prereqs.sh
Labels: Cleanup

#3412 Support block granularity for QuantizeLinear and DequantizeLinear
  docs/dev/onnx_operators.rst
  src/onnx/include/migraphx/onnx/quantize_dequantize_linear.hpp
  src/onnx/parse_dequantizelinear.cpp
  src/onnx/parse_quantizelinear.cpp
  src/onnx/quantize_dequantize_linear.cpp
  test/onnx/dequantizelinear_2d_blocked_with_zp_test.onnx
  test/onnx/dequantizelinear_3d_blocked_with_zp_runt_block_test.onnx
  test/onnx/dequantizelinear_scale_and_zp_shape_mismatch_test.onnx
  test/onnx/dequantizelinear_too_few_inputs_test.onnx
  test/onnx/dequantizelinear_too_many_inputs_test.onnx
  test/onnx/dequantizelinear_x_and_zp_type_mismatch_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/dequantizelinear_2d_blocked_with_zp_test.cpp
  test/onnx/parse/dequantizelinear_3d_blocked_with_zp_runt_block_test.cpp
  test/onnx/parse/dequantizelinear_negative_tests.cpp
  test/onnx/parse/quantizelinear_2d_blocked_with_zp_test.cpp
  test/onnx/parse/quantizelinear_3d_blocked_with_zp_runt_block_test.cpp
  test/onnx/parse/quantizelinear_negative_tests.cpp
  test/onnx/quantizelinear_2d_blocked_runt_block_test.onnx
  test/onnx/quantizelinear_2d_blocked_with_zp_test.onnx
  test/onnx/quantizelinear_3d_blocked_with_zp_runt_block_test.onnx
  test/onnx/quantizelinear_blocked_invalid_block_size_test.onnx
  test/onnx/quantizelinear_blocked_non_bc_axis_size_mismatch_test.onnx
  test/onnx/quantizelinear_blocked_x_and_scales_rank_mismatch_test.onnx
  test/onnx/quantizelinear_blocked_zero_block_size_test.onnx
  test/onnx/quantizelinear_output_dtype_and_zp_type_mismatch_test.onnx
  test/onnx/quantizelinear_per_axis_shape_mismatch_test.onnx
  test/onnx/quantizelinear_scales_and_zp_shape_mismatch_test.onnx
  test/onnx/quantizelinear_too_few_inputs_test.onnx
  test/onnx/quantizelinear_too_many_inputs_test.onnx
  test/onnx/verify/dequantizelinear_blocked_test.cpp
  test/onnx/verify/quantizelinear_blocked_test.cpp
  test/py/onnx_backend_test.py
Labels: high priority, Onnx Operators

#3480 Add check for fusable ops to attention fusion
  src/targets/gpu/fuse_mlir.cpp
  test/gpu/fuse_mlir.cpp
Labels: bugfix

#2780 gpu-driver documentation
  docs/gpu-driver/gpu-driver.rst
Labels: documentation, skip bot checks
