Repository ROCm/AMDMIGraphX, pull requests merged in 2024-08, with the labels that each got.

#3338 Update log2.cpp
  test/ref/log2.cpp
Labels: simple, skip bot checks

#3321 Bitwise_and operator
  src/CMakeLists.txt
  src/include/migraphx/op/bitwise_and.hpp
  src/include/migraphx/operators.hpp
  src/onnx/parse_binary_op.cpp
  test/onnx/bitwise_and_bcast_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/bitwise_and.cpp
  test/op_shape_test.cpp
  test/ref/bitwise_and.cpp
  test/verify/main.cpp
  test/verify/test_bitwise_and.cpp
Labels: Onnx Operators

#3129 Add ONNX parsing for SimplifiedLayerNormalization
  src/onnx/parse_simplified_layer_normalization.cpp
  src/targets/gpu/fuse_mlir.cpp
  test/onnx/gen_onnx.py
  test/onnx/include/onnx_test_utils.hpp
  test/onnx/parse/simplified_layer_normalization_invalid_input_test.cpp
  test/onnx/parse/simplified_layer_normalization_invalid_n_args_test.cpp
  test/onnx/parse/simplified_layer_normalization_test.cpp
  test/onnx/simplified_layer_normalization_invalid_input_test.onnx
  test/onnx/simplified_layer_normalization_invalid_n_args_test.onnx
  test/onnx/simplified_layer_normalization_test.onnx
  test/onnx/verify/simplified_layer_normalization.cpp
Labels: onnxruntime, Onnx Operators

#3333 Add constraints to type-erased class constructors
  src/include/migraphx/allocation_model.hpp
  src/include/migraphx/concat_opt.hpp
  src/include/migraphx/context.hpp
  src/include/migraphx/marker.hpp
  src/include/migraphx/operation.hpp
  src/include/migraphx/pass.hpp
  src/include/migraphx/schedule_model.hpp
  src/include/migraphx/stream_model.hpp
  src/include/migraphx/target.hpp
  tools/te.py
Labels: enhancement, Cleanup

#3354 fix licensing
  src/eliminate_contiguous.cpp
  src/include/migraphx/allocation_model.hpp
  src/include/migraphx/concat_opt.hpp
  src/include/migraphx/context.hpp
  src/include/migraphx/marker.hpp
  src/include/migraphx/operation.hpp
  src/include/migraphx/schedule_model.hpp
  src/include/migraphx/stream_model.hpp
  src/include/migraphx/target.hpp
  test/eliminate_contiguous_test.cpp
  tools/include/allocation_model.hpp
  tools/include/concat_opt.hpp
  tools/include/context.hpp
  tools/include/marker.hpp
  tools/include/operation.hpp
  tools/include/schedule_model.hpp
  tools/include/stream_model.hpp
  tools/include/target.hpp
  tools/te.py
Labels: skip bot checks

#3366 Docs: Fix sidebar title
  docs/conf.py
Labels: documentation

#3360 Assert assumption on other inputs of the pointwise while doing MLIR fusions
  src/targets/gpu/fuse_mlir.cpp
  test/gpu/fuse_mlir.cpp
Labels: high priority

#3342 Fix transposed padding
  src/include/migraphx/op/pad.hpp
  src/targets/gpu/jit/pad.cpp
Labels: bugfix

#3335 Upgrade CI to 6.1.3
  CMakeLists.txt
  Dockerfile
  Jenkinsfile
  cmake/EnableCompilerWarnings.cmake
  hip-clang.docker
  src/targets/gpu/device/topk.cpp
  test/api/CMakeLists.txt
  tools/docker/sles.docker
  tools/install_prereqs.sh
Labels: Continous Integration

#3387 Add fixes for layout nhwc
  src/layout_nhwc.cpp
  test/layout_nhwc.cpp
Labels: bugfix, Perf Improve, nhwc

#3265 [BACKPORT] Bump rocmlir SHA to fix navi FP32 verify failure
  requirements.txt
Labels: high priority

#3391 Add missing return in reduce_reshape pass
  src/fuse_reduce.cpp
  test/fuse_reduce.cpp
Labels: bugfix

#3368 Optimize transposed concat
  src/targets/gpu/jit/concat.cpp
  test/verify/test_concat_nhwc.cpp
Labels: nhwc

#3140 Add ONNX parsing for SkipSimplifiedLayerNormalization
  src/onnx/parse_skip_simplified_layer_normalization.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/skip_simplified_layer_normalization_invalid_input_test.cpp
  test/onnx/parse/skip_simplified_layer_normalization_invalid_n_args_test.cpp
  test/onnx/parse/skip_simplified_layer_normalization_test.cpp
  test/onnx/skip_simplified_layer_normalization_bias_test.onnx
  test/onnx/skip_simplified_layer_normalization_invalid_input_test.onnx
  test/onnx/skip_simplified_layer_normalization_invalid_n_args_test.onnx
  test/onnx/skip_simplified_layer_normalization_test.onnx
  test/onnx/verify/skip_simplified_layer_normalization.cpp
Labels: Onnx Operators

#3400 Update licenses to fix CI license check failure
  src/insert_pad.cpp
  src/layout_nhwc.cpp
  src/onnx/parse_binary_op.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/debug.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/iota_iterator.hpp
  test/layout_nhwc.cpp
  test/ref/pooling.cpp
Labels: bugfix

#3401 Move addition of repo before zypper install command for sles docker
  tools/docker/sles.docker
Labels: bugfix

#3404 Fix windows build error due to extra copy caused by missing const& for iterator
  src/targets/gpu/fuse_mlir.cpp
Labels: Windows, UAI

#3389 Pooling improvements
  docs/dev/env_vars.rst
  src/targets/gpu/jit/pooling.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/pooling.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/reduce.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/tuple.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/vec.hpp
  src/targets/gpu/lowering.cpp
  test/verify/test_avg_pooling_asym_pad.cpp
  test/verify/test_avg_pooling_nhwc.cpp
  test/verify/test_max_pooling_asym_pad.cpp
Labels: Perf Improve, nhwc

#3343 Move auto_contiguous before lowering
  src/include/migraphx/shape.hpp
  src/shape.cpp
  src/targets/gpu/code_object_op.cpp
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/target.cpp
  test/shape_test.cpp
Labels: nhwc
