Repository ROCm/AMDMIGraphX, pull requests merged in 2024-01, with the labels that each got.

#2513 Update MatMulInteger op parsing
  src/include/migraphx/op/quant_dot.hpp
  src/onnx/parse_matmul.cpp
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/target.cpp
  test/onnx/gen_onnx.py
  test/onnx/matmulinteger_uns_test.onnx
  test/onnx/matmulinteger_uns_zp_test.onnx
  test/onnx/verify/matmulinteger_uns_test.cpp
  test/onnx/verify/matmulinteger_uns_zp_test.cpp
  test/py/onnx_backend_test.py
Labels: bugfix

#2590 Make the tbb dependency conditional
  CMakeLists.txt
  src/CMakeLists.txt
Labels: dependencies

#2521 Add Llama-2 example
  examples/transformers/README.md
  examples/transformers/python_llama2/README.md
  examples/transformers/python_llama2/gradio_app.py
  examples/transformers/python_llama2/gradio_requirements.txt
  examples/transformers/python_llama2/llama2.ipynb
  examples/transformers/python_llama2/requirements.txt
  examples/transformers/python_llama2/txtgen.py
Labels: skip bot checks

#2498 Add Whisper example
  examples/diffusion/python_stable_diffusion_21/sd21.ipynb
  examples/diffusion/python_stable_diffusion_21/txt2img.py
  examples/transformers/README.md
  examples/transformers/python_whisper/README.md
  examples/transformers/python_whisper/asr.py
  examples/transformers/python_whisper/download_samples.sh
  examples/transformers/python_whisper/download_whisper.py
  examples/transformers/python_whisper/gradio_app.py
  examples/transformers/python_whisper/gradio_requirements.txt
  examples/transformers/python_whisper/requirements.txt
  examples/transformers/python_whisper/whisper.ipynb
Labels: skip bot checks

#2415 Add layout attribute support for GRU operator
  src/onnx/parse_gru.cpp
  test/onnx/gen_onnx.py
  test/onnx/gru_bi_5arg_layout_test.onnx
  test/onnx/gru_bi_layout_test.onnx
  test/onnx/gru_f_3arg_layout_test.onnx
  test/onnx/gru_f_layout_test.onnx
  test/onnx/gru_r_4arg_layout_test.onnx
  test/onnx/gru_r_layout_test.onnx
  test/onnx/onnx_gru_bi_1.onnx
  test/onnx/onnx_gru_bi_2.onnx
  test/onnx/onnx_gru_bi_3.onnx
  test/onnx/onnx_gru_reverse_1.onnx
  test/onnx/onnx_rnn_test.cpp
  test/py/onnx_backend_test.py
  test/ref/rnn_ops.cpp
  test/verify/test_gru_bidirct.cpp
  test/verify/test_gru_bidirct_3args.cpp
  test/verify/test_gru_bidirct_3args_layout.cpp
  test/verify/test_gru_bidirct_3args_und.cpp
  test/verify/test_gru_bidirct_default_actv1.cpp
  test/verify/test_gru_bidirct_layout.cpp
  test/verify/test_gru_bidirct_seq1.cpp
  test/verify/test_gru_forward_3args_layout.cpp
  test/verify/test_gru_forward_layout.cpp
  test/verify/test_gru_reverse_3args_layout.cpp
  test/verify/test_gru_reverse_last_layout.cpp
Labels: enhancement

#2589 Tanh GELU matcher and matcher.has_value() fix
  src/include/migraphx/match/gelu_erf.hpp
  src/include/migraphx/match/gelu_tanh.hpp
  src/include/migraphx/matcher.hpp
  src/include/migraphx/rewrite_gelu.hpp
  src/quantization.cpp
  src/rewrite_gelu.cpp
  src/simplify_algebra.cpp
  src/targets/gpu/target.cpp
  test/matcher.cpp
  test/quantization.cpp
  test/rewrite_gelu_test.cpp
  test/verify/test_conv_bn.cpp
  test/verify/test_conv_bn_add.cpp
  test/verify/test_conv_bn_relu_pooling.cpp
  test/verify/test_conv_bn_relu_pooling2.cpp
  tools/accuracy/accuracy_checker.py
Labels: bugfix, Matchers, Cleanup

#2627 Remove cmake_path since its not supported on older cmake
  cmake/Embed.cmake
Labels: bugfix

#2643 Update onnxrt sync github action
  .github/workflows/sync-onnxrt-main.yaml
Labels: bugfix, skip bot checks

#2645 Add macro to Doxyfile to fix doxygen docs
  docs/doxygen/Doxyfile
Labels: documentation

#2047 Add resnet50 example used with onnxruntime inferencing
  examples/onnxruntime/resnet50/README.md
  examples/onnxruntime/resnet50/images/bird.jpg
  examples/onnxruntime/resnet50/images/guitar.jpg
  examples/onnxruntime/resnet50/images/guitar2.jpg
  examples/onnxruntime/resnet50/images/guitar3.jpg
  examples/onnxruntime/resnet50/images/scope.jpg
  examples/onnxruntime/resnet50/images/screwdrivers.jpg
  examples/onnxruntime/resnet50/prereq_steps.sh
  examples/onnxruntime/resnet50/resnet50.py
Labels: onnxruntime, skip bot checks, DeepLearningModels

#2647 Fixing export API symbols from dynamic library
  src/include/migraphx/pass.hpp
  tools/include/pass.hpp
Labels: Windows

#2630 Adding additional check, if the graph is empty
  src/tf/tf_parser.cpp
  test/tf/tf_test.cpp
Labels: Windows

#2648 Enable Asymmetric Quantization
  src/simplify_qdq.cpp
  test/quantization.cpp
  test/simplify_qdq_test.cpp
Labels: enhancement

#2678 Add normalize to quantization passes
  src/quantization.cpp
Labels: bugfix

#2682 Fix compute shape for the fused_concat
  src/fuse_concat.cpp
  test/fuse_concat.cpp
Labels: bugfix

#2690 Fix compute_shape of `mlir_op`
  src/targets/gpu/compile_ops.cpp
  src/targets/gpu/fuse_mlir.cpp
Labels: high priority
