Repository ROCm/AMDMIGraphX, pull requests merged in 2024-03, with the labels that each got.

#2802 Add fix for find_transpose_contiguous_reshaper_unary in simplify_reshapes pass
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: bugfix

#2855 Fix after merging #2469: remove extra spaces from option strings
  src/targets/gpu/jit/roialign.cpp
Labels: bugfix, high priority

#2730 PackInt4 Operator
  src/CMakeLists.txt
  src/include/migraphx/op/pack_int4.hpp
  src/include/migraphx/tensor_view.hpp
  test/op_shape_test.cpp
  test/ref/pack_int4.cpp
Labels: INT4

#2782 Enable mlir by default for gemms with small K
  docs/dev/env_vars.rst
  src/split_single_dyn_dim.cpp
  src/targets/gpu/fuse_mlir.cpp
Labels: Perf Improve

#2828 Remove list initialization for prefix_scan_sum
  src/include/migraphx/builtin.hpp
  src/include/migraphx/op/if_op.hpp
  src/include/migraphx/op/loop.hpp
  src/include/migraphx/op/run_on_target.hpp
  src/include/migraphx/op/topk.hpp
  src/include/migraphx/op/unique.hpp
  src/include/migraphx/shape.hpp
  src/include/migraphx/type_traits.hpp
  src/shape.cpp
  src/targets/fpga/vitis_ai_adapter.cpp
  src/targets/gpu/include/migraphx/gpu/prefix_scan_sum.hpp
  test/include/basic_ops.hpp
  test/op_shape_test.cpp
  test/run_loop_test.cpp
Labels: bugfix, high priority

#2871 Onnx backend test update
  test/py/onnx_backend_test.py
Labels: onnx, Continous Integration

#2716 Expose FP8 API to Python
  docs/reference/py.rst
  src/py/migraphx_py.cpp
  test/py/CMakeLists.txt
  test/py/test_autocast_fp8.py
Labels: FP8

#2880 Supported ONNX operators list
  docs/dev/onnx_operators.rst
Labels: onnx, documentation, skip bot checks

#2815 Use clang++ from HIP SDK on Windows as a C++ compiler
  src/CMakeLists.txt
  src/compile_src.cpp
  src/include/migraphx/compile_src.hpp
  src/include/migraphx/tmp_dir.hpp
  src/targets/gpu/CMakeLists.txt
Labels: Windows

#2887 fix tidy complaint
  src/simplify_qdq.cpp
Labels: bugfix, simple

#2886 Fuse layout with pointwise op
  src/targets/gpu/fuse_ops.cpp
  test/gpu/fuse_ops.cpp
  test/verify/test_pointwise_conv_nhwc.cpp
Labels: Perf Improve

#2698 Improve reduction fusion with reshape operators
  src/common_dims.cpp
  src/fuse_pointwise.cpp
  src/fuse_reduce.cpp
  src/include/migraphx/common_dims.hpp
  src/include/migraphx/module.hpp
  src/include/migraphx/rewrite_reshapes.hpp
  src/module.cpp
  test/common_dims.cpp
  test/fuse_pointwise.cpp
  test/fuse_reduce.cpp
Labels: enhancement, high priority

#2889 Fuse contiguous and layout with pointwise
  src/targets/gpu/fuse_ops.cpp
  test/gpu/fuse_ops.cpp
  test/verify/test_trans_convert_gemm.cpp
Labels: high priority, Perf Improve

#2896 Fixes to parse DynamicQuantizeLinear
  src/onnx/parse_dynamicquantizelinear.cpp
  test/onnx/parse/dynamicquantizelinear_2d_test.cpp
Labels: bugfix, high priority

#2907 pick up 1454 from rocMLIR
  requirements.txt
Labels: high priority

#2657 Resize matcher
  src/include/migraphx/op/resize.hpp
  src/simplify_dyn_ops.cpp
  test/onnx/verify/resize_outsize_test.cpp
  test/ref/resize.cpp
  test/simplify_dyn_ops_test.cpp
  test/verify/main.cpp
  test/verify/test_resize_dyn.cpp
Labels: enhancement, Matchers

#2924 Skip FP8 dot/gemm for MLIR and offload them to rocBLAS
  src/targets/gpu/fuse_mlir.cpp
Labels: bugfix, simple
