Repository ROCm/AMDMIGraphX, pull requests merged in 2024-07, with the labels that each got.

#2990 Add Model Zoo testing support
  tools/model_zoo/README.md
  tools/model_zoo/onnx_zoo/README.md
  tools/model_zoo/onnx_zoo/test_models.sh
  tools/model_zoo/test_generator/README.md
  tools/model_zoo/test_generator/generate.py
  tools/model_zoo/test_generator/requirements.txt
  tools/model_zoo/test_generator/sample_generator/__init__.py
  tools/model_zoo/test_generator/sample_generator/dataset/__init__.py
  tools/model_zoo/test_generator/sample_generator/dataset/base.py
  tools/model_zoo/test_generator/sample_generator/dataset/coco.py
  tools/model_zoo/test_generator/sample_generator/dataset/imagenet.py
  tools/model_zoo/test_generator/sample_generator/dataset/librispeech.py
  tools/model_zoo/test_generator/sample_generator/dataset/prompts.py
  tools/model_zoo/test_generator/sample_generator/dataset/squad.py
  tools/model_zoo/test_generator/sample_generator/generator/__init__.py
  tools/model_zoo/test_generator/sample_generator/generator/diffusion.py
  tools/model_zoo/test_generator/sample_generator/generator/generic.py
  tools/model_zoo/test_generator/sample_generator/model/__init__.py
  tools/model_zoo/test_generator/sample_generator/model/audio.py
  tools/model_zoo/test_generator/sample_generator/model/base.py
  tools/model_zoo/test_generator/sample_generator/model/diffusion.py
  tools/model_zoo/test_generator/sample_generator/model/hybrid.py
  tools/model_zoo/test_generator/sample_generator/model/image.py
  tools/model_zoo/test_generator/sample_generator/model/preprocess.py
  tools/model_zoo/test_generator/sample_generator/model/text.py
  tools/model_zoo/test_generator/sample_generator/utils/__init__.py
  tools/model_zoo/test_generator/sample_generator/utils/utils.py
  tools/model_zoo/test_generator/test_models.sh
Labels: skip bot checks

#3237 fix warning about wrong use of export
  src/include/migraphx/generate.hpp
Labels: bugfix, high priority, Windows, UAI

#3242 fix bug in find_concat_op when input broadcasts are on different axes
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: bugfix, TorchMIGraphX

#3226 Update README.md to add -DGPU_TARGETS=$(/opt/rocm/bin/rocminfo | grep -o -m1 'gfx.*') for rbuild develop
  README.md
Labels: documentation, simple

#3244 find_splits bugfix
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: bugfix

#3253 Windows/fix memory issue
  src/targets/gpu/hip.cpp
Labels: Windows, UAI

#3256 use unitAttr for split-k attribute
  src/targets/gpu/mlir.cpp
  test/gpu/mlir.cpp
Labels: simple, skip bot checks

#3274 Update Onnxruntime MIGraphx + ROCm EP docker to 6.1.3
  tools/docker/migraphx_with_onnxruntime_pytorch.docker
Labels: bugfix, Continous Integration

#3281 Fix dpp reduce navi21
  src/targets/gpu/kernels/include/migraphx/kernels/reduce.hpp
  test/verify/test_reduce_op_small.cpp
Labels: bugfix

#3278 update python module versioning for dev builds
  src/py/migraphx_py.cpp
Labels: TorchMIGraphX

#3260 Fix --enable-offload-copy warning
  src/driver/main.cpp
  src/program.cpp
Labels: bugfix, simple

#3259 Bump rocm-cmake commit hash to include private lib changes
  dev-requirements.txt
Labels: bugfix, high priority

#3295 2024 license update
  test/gpu/fuse_mlir.cpp
Labels: simple

#3315 Temporary workaround on rocMLIR linking issue
  src/targets/gpu/CMakeLists.txt
Labels: bug, high priority, Windows, UAI, rocMLIR

#3312 Update documentation requirements
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, dependencies

#2936 Add support for Scan operator
  docs/dev/onnx_operators.rst
  src/CMakeLists.txt
  src/include/migraphx/op/loop.hpp
  src/include/migraphx/op/scan_slice.hpp
  src/include/migraphx/operators.hpp
  src/include/migraphx/run_loop.hpp
  src/onnx/parse_scan.cpp
  src/targets/gpu/loop.cpp
  src/targets/gpu/lowering.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/scan_test.cpp
  test/onnx/scan_arg_count_mismatch_test.onnx
  test/onnx/scan_arg_shapes_mismatch_test.onnx
  test/onnx/scan_input_axes_lens_mismatch_test.onnx
  test/onnx/scan_invalid_input_axes_len_test.onnx
  test/onnx/scan_invalid_input_axes_vals_test.onnx
  test/onnx/scan_invalid_input_dirs_len_test.onnx
  test/onnx/scan_invalid_input_dirs_vals_test.onnx
  test/onnx/scan_invalid_output_axes_len_test.onnx
  test/onnx/scan_invalid_output_axes_vals_test.onnx
  test/onnx/scan_invalid_output_dirs_len_test.onnx
  test/onnx/scan_invalid_output_dirs_vals_test.onnx
  test/onnx/scan_test1.onnx
  test/onnx/scan_test2.onnx
  test/onnx/scan_test3.onnx
  test/onnx/scan_test4.onnx
  test/onnx/scan_test5.onnx
  test/onnx/scan_test6.onnx
  test/onnx/scan_test7.onnx
  test/onnx/verify/scan_test.cpp
  test/op_shape_test.cpp
  test/py/onnx_backend_test.py
  test/ref/scan_slice.cpp
  test/run_loop_test.cpp
  test/verify/test_scan_slice.cpp
Labels: Onnx Operators

#3324 Fix matcher Bindings when doing attention fusion
  src/targets/gpu/prefuse_ops.cpp
Labels: enhancement, bugfix

#3325 Get correct data type for lane reductions
  src/targets/gpu/kernels/include/migraphx/kernels/reduce.hpp
Labels: bugfix
