Repository ROCm/AMDMIGraphX, pull requests merged in 2024-02, with the labels that each got.

#2675 Clip to max_int on overflow of element_space for dynamic shape
  examples/onnxruntime/dataset/imagenet_classes.txt
  src/include/migraphx/shape.hpp
  src/shape.cpp
  test/shape_test.cpp
Labels: bugfix

#2696 use lower tolerance for zero detection in simplify_algebra
  src/include/migraphx/matcher.hpp
  src/simplify_algebra.cpp
  test/matcher.cpp
Labels: high priority

#2626 Cleanup LSTM and RNN activation functions
  src/onnx/parse_lstm.cpp
  src/onnx/parse_rnn.cpp
  test/onnx/gen_onnx.py
  test/onnx/gru_f_1af_test.onnx
  test/onnx/lstm_bi_layout_cell_test.onnx
  test/onnx/lstm_bi_layout_last_test.onnx
  test/onnx/lstm_f_1af_test.onnx
  test/onnx/onnx_lstm_bi.onnx
  test/onnx/onnx_lstm_bi1af.onnx
  test/onnx/onnx_lstm_bi2af.onnx
  test/onnx/onnx_lstm_bi3af.onnx
  test/onnx/onnx_lstm_bi3args.onnx
  test/onnx/onnx_lstm_bi4af.onnx
  test/onnx/onnx_lstm_bi4args.onnx
  test/onnx/onnx_lstm_bi5af.onnx
  test/onnx/onnx_lstm_bi5args.onnx
  test/onnx/onnx_lstm_bi6af.onnx
  test/onnx/onnx_lstm_bi6args.onnx
  test/onnx/onnx_lstm_bi7args.onnx
  test/onnx/onnx_lstm_f1af.onnx
  test/onnx/onnx_lstm_f2af.onnx
  test/onnx/onnx_rnn_3args.onnx
  test/onnx/onnx_rnn_5args.onnx
  test/onnx/onnx_rnn_forward.onnx
  test/onnx/onnx_rnn_reverse.onnx
  test/onnx/onnx_rnn_test.cpp
  test/onnx/rnn_bi_1af_test.onnx
  test/onnx/rnn_f_5arg_layout_test.onnx
  test/onnx/rnn_f_default_af_test.onnx
  test/onnx/rnn_f_layout_test.onnx
  test/onnx/rnn_r_3arg_layout_test.onnx
  test/onnx/rnn_r_layout_test.onnx
  test/ref/rnn_ops.cpp
  test/verify/test_gru_bidirct_default_actv1.cpp
  test/verify/test_lstm_bidirct_3args.cpp
  test/verify/test_lstm_bidirct_3args_layout.cpp
  test/verify/test_lstm_bidirct_3args_und.cpp
  test/verify/test_lstm_bidirct_default_actv1.cpp
  test/verify/test_lstm_bidirct_default_actv2.cpp
  test/verify/test_lstm_bidirct_hs.cpp
  test/verify/test_lstm_bidirct_last.cpp
  test/verify/test_lstm_bidirct_last_layout.cpp
  test/verify/test_lstm_bidirct_seq1.cpp
  test/verify/test_lstm_forward_default_actv1.cpp
  test/verify/test_rnn_3args.cpp
  test/verify/test_rnn_4args.cpp
  test/verify/test_rnn_4args_layout.cpp
  test/verify/test_rnn_5args.cpp
  test/verify/test_rnn_forward.cpp
  test/verify/test_rnn_forward10.cpp
  test/verify/test_rnn_forward_layout.cpp
  test/verify/test_rnn_reverse.cpp
  test/verify/test_rnn_reverse2.cpp
  test/verify/test_rnn_reverse_layout.cpp
  test/verify/test_rnn_sql_1.cpp
  test/verify/test_rnn_sql_1_layout.cpp
  test/verify/test_rnn_sql_2.cpp
  test/verify/test_var_sl_gru_bidirct.cpp
Labels: bugfix, Cleanup

#2673 Rewrite softmax
  src/CMakeLists.txt
  src/include/migraphx/rewrite_reduce.hpp
  src/rewrite_reduce.cpp
  src/targets/gpu/compile_gen.cpp
  src/targets/gpu/include/migraphx/gpu/compile_gen.hpp
  src/targets/gpu/target.cpp
  test/rewrite_reduce.cpp
Labels: enhancement

#1783 Enable Navi32 in CI
  Jenkinsfile
  test/py/CMakeLists.txt
Labels: roadmap, revisit, Continous Integration

#2644 Simple container for Onnxrt + MIGraphX + Torch for Docker…
  tools/docker/migraphx_with_onnxruntime_pytorch.docker
Labels: roadmap, skip bot checks

#2745 Fix test failure on develop
  src/targets/gpu/compile_gen.cpp
Labels: bugfix

#2781 Remove same dynamic output shapes check
  test/verify/run_verify.cpp
Labels: simple

#2775 Add vim syntax file for MIGX IR
  tools/syntax/migx.vim
Labels: simple, skip bot checks

#2677 Exclude requirements.in file for clang format
  tools/format.py
Labels: bugfix, Continous Integration

#2769 Simplify "slice(concat(x, y,...))" to x if applicable
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: Perf Improve

#2768 Eliminate collapsing batch dimensions for dot op
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: Perf Improve

#2748 match gemm_softmax_gemm when there is no scale
  src/targets/gpu/include/migraphx/gpu/prefuse_ops.hpp
  src/targets/gpu/prefuse_ops.cpp
  test/gpu/prefuse_ops.cpp
Labels: Perf Improve

#2793 Fix compile fileutils test on Windows
  test/fileutils.cpp
Labels: bug, bugfix, Windows

#2791 Bump MIGraphX version
  CMakeLists.txt
Labels: skip bot checks

#2800 Fix vim syntax for `hip::copy_literal`
  tools/syntax/migx.vim
Labels: simple, skip bot checks

#2795 Buffer read/write: use fs::path instead of std::string for filenames
  src/compile_src.cpp
  src/dynamic_loader.cpp
  src/file_buffer.cpp
  src/include/migraphx/file_buffer.hpp
  src/onnx/include/migraphx/onnx/onnx_parser.hpp
  src/onnx/onnx_parser.cpp
  src/targets/gpu/compile_hip.cpp
Labels: Windows

#2792 Suppress warning message when ParallelSTL is not found
  CMakeLists.txt
Labels: Windows

#2783 Fix Pad op parsing
  src/onnx/parse_pad.cpp
  test/onnx/gen_onnx.py
  test/onnx/pad_undef_const_val_test.onnx
  test/onnx/parse/pad_undef_const_val_test.cpp
Labels: bugfix

#2475 Split multiple same dyn_dim
  src/include/migraphx/split_single_dyn_dim.hpp
  src/split_single_dyn_dim.cpp
  test/split_single_dyn_dim_test.cpp
Labels: enhancement

#2639 Fuse group convolution
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
  test/verify/test_conv_concat.cpp
Labels: enhancement

#2816 Retry tmp_dir removal on failure
  src/tmp_dir.cpp
Labels: Windows

#2835 unsigned long is 32bit on Windows
  src/targets/gpu/kernels/include/migraphx/kernels/type_traits.hpp
Labels: bugfix, Windows

#2840 tests: sort programs before compaing content
  test/quantization.cpp
  test/split_single_dyn_dim_test.cpp
Labels: Windows

#2655 Update Reshape(dynamic_shape) to allow more than one non-fixed dynamic_dimension
  src/include/migraphx/op/reshape.hpp
  test/op_shape_test.cpp
Labels: simple

#2841 Suppress compilation warning about result not read
  test/ref/resize.cpp
Labels: Windows
