Repository ROCm/AMDMIGraphX, pull requests merged in 2024-06, with the labels that each got.

#3147 Fix input args capture when replacing split module
  src/targets/gpu/jit/mlir.cpp
Labels: high priority

#3144 Disable rocBLAS by default on Windows
  CMakeLists.txt
Labels: Windows, UAI

#2866 Fix targets registration on Windows
  src/include/migraphx/register_target.hpp
  test/CMakeLists.txt
  test/register_target.cpp
Labels: Windows, UAI

#2861 Export symbol from DLL in test_jit
  test/jit.cpp
Labels: Windows, UAI

#3153 Change std::stoul to std::stoull in onnx_parser
  src/onnx/onnx_parser.cpp
Labels: Windows, UAI

#3138 Add MLIR conv3d support
  src/targets/gpu/fuse_mlir.cpp
Labels: UAI

#3160 Increased stack size for migraphx-hiprtc-driver to 4MB on Windows
  src/targets/gpu/hiprtc/CMakeLists.txt
Labels: Windows, UAI

#3162 fix inner broadcast bug
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: bugfix

#3041 Add FP8 ONNX tests
  test/onnx/add_fp8_test.onnx
  test/onnx/binary_dyn_brcst_mul_fp8_test.onnx
  test/onnx/conv_1d_fp8_test.onnx
  test/onnx/cos_fp8_test.onnx
  test/onnx/div_fp8_test.onnx
  test/onnx/gemm_fp8_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/globalavgpool_fp8_test.onnx
  test/onnx/globalmaxpool_fp8_test.onnx
  test/onnx/parse/add_fp8_test.cpp
  test/onnx/parse/binary_dyn_brcst_mul_fp8_test.cpp
  test/onnx/parse/conv_1d_fp8_test.cpp
  test/onnx/parse/cos_fp8_test.cpp
  test/onnx/parse/div_fp8_test.cpp
  test/onnx/parse/gemm_fp8_test.cpp
  test/onnx/parse/globalavgpool_fp8_test.cpp
  test/onnx/parse/globalmaxpool_fp8_test.cpp
  test/onnx/parse/reducemax_fp8_test.cpp
  test/onnx/parse/reducesum_fp8_test.cpp
  test/onnx/parse/shrink_fp8_test.cpp
  test/onnx/parse/sin_fp8_test.cpp
  test/onnx/parse/size_fp8_test.cpp
  test/onnx/parse/sqrt_fp8_test.cpp
  test/onnx/reducemax_fp8_test.onnx
  test/onnx/reducesum_fp8_test.onnx
  test/onnx/shrink_fp8_test.onnx
  test/onnx/sin_fp8_test.onnx
  test/onnx/size_fp8_test.onnx
  test/onnx/sqrt_fp8_test.onnx
  test/onnx/verify/add_fp8_test.cpp
  test/onnx/verify/gemm_fp8_test.cpp
  test/onnx/verify/shrink_fp8_test.cpp
  test/onnx/verify/size_fp8_test.cpp
Labels: FP8

#3179 fix contribute link in index.rst
  docs/index.rst
Labels: documentation

#3180 fix contribute link
  docs/index.rst
Labels: documentation

#3181 fix contribute link
  docs/index.rst
Labels: documentation

#3174 fix dot_broadcast bug
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: bug

#2809 mul add transpose dot matcher
  src/simplify_reshapes.cpp
  test/optimize_module_test.cpp
  test/simplify_reshapes_test.cpp
Labels: Perf Improve

#3184 Make libmigraphx_onnx.so a private library
  src/onnx/CMakeLists.txt
Labels: enhancement, bugfix, simple

#3031 Refactor 1 arg dynamic reshape
  src/include/migraphx/op/reshape.hpp
  src/include/migraphx/sat_ops.hpp
  test/op_shape_test.cpp
Labels: roadmap

#2909 Add support for GridSample operator
  docs/dev/onnx_operators.rst
  src/onnx/parse_gridsample.cpp
  test/onnx/gen_onnx.py
  test/onnx/gridsample_aligncorners_true_test.onnx
  test/onnx/gridsample_bicubic_test.onnx
  test/onnx/gridsample_bilinear_align_corners_0_additional_1_test.onnx
  test/onnx/gridsample_bilinear_align_corners_1_additional_1_test.onnx
  test/onnx/gridsample_bilinear_test.onnx
  test/onnx/gridsample_border_padding_test.onnx
  test/onnx/gridsample_half_test.onnx
  test/onnx/gridsample_int_test.onnx
  test/onnx/gridsample_mismatching_dims_test.onnx
  test/onnx/gridsample_nearest_align_corners_0_additional_1_test.onnx
  test/onnx/gridsample_nearest_align_corners_1_additional_1_test.onnx
  test/onnx/gridsample_nearest_test.onnx
  test/onnx/gridsample_reflection_padding_test.onnx
  test/onnx/gridsample_simple_test.onnx
  test/onnx/gridsample_test.onnx
  test/onnx/gridsample_volumetric_nearest_align_corners_0_test.onnx
  test/onnx/gridsample_wrong_grid_type_test.onnx
  test/onnx/gridsample_zeros_padding_test.onnx
  test/onnx/parse/gridsample_bicubic_test.cpp
  test/onnx/parse/gridsample_mismatching_dims_test.cpp
  test/onnx/parse/gridsample_volumetric_nearest_align_corners_0_test.cpp
  test/onnx/parse/gridsample_wrong_grid_type_test.cpp
  test/onnx/verify/gridsample_aligncorners_true_test.cpp
  test/onnx/verify/gridsample_bilinear_align_corners_0_additional_1_test.cpp
  test/onnx/verify/gridsample_bilinear_align_corners_1_additional_1_test.cpp
  test/onnx/verify/gridsample_bilinear_test.cpp
  test/onnx/verify/gridsample_border_padding_test.cpp
  test/onnx/verify/gridsample_half_test.cpp
  test/onnx/verify/gridsample_int_test.cpp
  test/onnx/verify/gridsample_nearest_align_corners_0_additional_1_test.cpp
  test/onnx/verify/gridsample_nearest_align_corners_1_additional_1_test.cpp
  test/onnx/verify/gridsample_nearest_test.cpp
  test/onnx/verify/gridsample_reflection_padding_test.cpp
  test/onnx/verify/gridsample_test.cpp
  test/onnx/verify/gridsample_zeros_padding_test.cpp
  test/py/onnx_backend_test.py
Labels: Onnx Operators

#3192 Update cmake to 3.27.0
  Dockerfile
  src/onnx/CMakeLists.txt
Labels: onnxruntime, simple

#3124 Add remove MIOpen build option
  CMakeLists.txt
  src/CMakeLists.txt
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/abs.cpp
  src/targets/gpu/fuse_ops.cpp
  src/targets/gpu/hip.cpp
  src/targets/gpu/hiprtc/CMakeLists.txt
  src/targets/gpu/include/migraphx/gpu/abs.hpp
  src/targets/gpu/include/migraphx/gpu/context.hpp
  src/targets/gpu/include/migraphx/gpu/convolution.hpp
  src/targets/gpu/include/migraphx/gpu/lrn.hpp
  src/targets/gpu/include/migraphx/gpu/miopen.hpp
  src/targets/gpu/include/migraphx/gpu/pooling.hpp
  src/targets/gpu/jit/roialign.cpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/lrn.cpp
  src/targets/gpu/pooling.cpp
  src/targets/gpu/target.cpp
  test/gpu/fuse_ops.cpp
Labels: UAI

#3201 Softmax JIT kernel speedup: removal of an intermediate result.
  src/targets/gpu/kernels/include/migraphx/kernels/softmax.hpp
Labels: Perf Improve

#3206 Implement `reduce_any` and `reduce_all`
  src/CMakeLists.txt
  src/include/migraphx/float8.hpp
  src/include/migraphx/op/reduce_all.hpp
  src/include/migraphx/op/reduce_any.hpp
  src/targets/gpu/compile_gen.cpp
  src/targets/gpu/jit/reduce.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/ops.hpp
  test/fp8e4m3fn.cpp
  test/fp8e4m3fnuz.cpp
  test/fp8e5m2.cpp
  test/fp8e5m2fnuz.cpp
  test/ref/reduce_all.cpp
  test/ref/reduce_any.cpp
  test/verify/test_reduce_op_large.cpp
  test/verify/test_reduce_op_small.cpp
Labels: TorchMIGraphX

#3215 Bump rocm-cmake commit hash to include changes for private libs
  dev-requirements.txt
Labels: bugfix

#3191 Add onnx_options external data path setter
  src/api/api.cpp
  src/api/include/migraphx/migraphx.h
  src/api/include/migraphx/migraphx.hpp
  src/api/migraphx.py
  src/py/migraphx_py.cpp
  test/api/test_cpu.cpp
  tools/api/api.cpp
  tools/api/migraphx.h
Labels: skip bot checks, UAI

#3221 Disable FP8 gemm-add test temporarily
  test/verify/test_gemm_add.cpp
Labels: bug

#3225 Fix set_external_data_path test
  test/api/test_cpu.cpp
Labels: UAI
