Repository ROCm/AMDMIGraphX, pull requests merged in 2024-10, with the labels that each got.

#3428 Move auto_contiguous before lowering
  src/targets/gpu/target.cpp
Labels: bugfix, Perf Improve

#2351 Optimize docker image building in Jenkinsfile
  Jenkinsfile
Labels: high priority, Continous Integration

#3511 Dont use global counter in fuse_mlir
  src/targets/gpu/fuse_mlir.cpp
  test/gpu/fuse_mlir.cpp
Labels: INT4

#3515 Bump MLIR for conv3d bugfix
  requirements.txt
Labels: bugfix

#3516 Run eliminate_identity before simplify_qdq
  src/targets/gpu/target.cpp
Labels: INT4

#3496 Add support for MatMulNBits
  src/onnx/parse_matmulnbits.cpp
  src/targets/gpu/lowering.cpp
  test/onnx/gen_onnx.py
  test/onnx/matmulnbits_block_size_not_power_of_two_test.onnx
  test/onnx/matmulnbits_block_size_too_small_test.onnx
  test/onnx/matmulnbits_bmm_test.onnx
  test/onnx/matmulnbits_invalid_b_dims_test.onnx
  test/onnx/matmulnbits_invalid_bits_value_test.onnx
  test/onnx/matmulnbits_invalid_scales_dims_test.onnx
  test/onnx/matmulnbits_invalid_zp_dims_test.onnx
  test/onnx/matmulnbits_mm2_test.onnx
  test/onnx/matmulnbits_mm_test.onnx
  test/onnx/matmulnbits_vm_test.onnx
  test/onnx/parse/matmulnbits_negative_tests.cpp
  test/onnx/parse/matmulnbits_tests.cpp
  test/onnx/verify/matmulnbits_tests.cpp
Labels: roadmap, high priority, Onnx Operators

#3507 MLIR fusion for int4
  src/targets/gpu/fuse_mlir.cpp
  test/gpu/fuse_mlir.cpp
  test/onnx/gen_onnx.py
  test/onnx/int4_const_identity_block_sz_1_qdq_test.onnx
  test/onnx/int4_const_identity_block_sz_2_qdq_test.onnx
  test/onnx/int4_const_identity_qdq_test.onnx
Labels: INT4

#3425 Add GroupQueryAttention with KV-Cache
  src/CMakeLists.txt
  src/include/migraphx/op/group_query_attention.hpp
  src/include/migraphx/operators.hpp
  src/onnx/parse_group_query_attention.cpp
  src/onnx/parse_simplified_layer_normalization.cpp
  src/onnx/parse_skip_simplified_layer_normalization.cpp
  src/targets/gpu/compile_hip_code_object.cpp
  src/targets/gpu/include/migraphx/gpu/compile_hip_code_object.hpp
  src/targets/gpu/include/migraphx/gpu/group_query_attention.hpp
  src/targets/gpu/jit/compute_attention_probabilities.cpp
  src/targets/gpu/jit/compute_attention_scores.cpp
  src/targets/gpu/jit/concat_past_present.cpp
  src/targets/gpu/jit/gqa_rotary_embedding.cpp
  src/targets/gpu/jit/gqa_softmax.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/compute_attention_probabilities.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/compute_attention_scores.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/concat_past_present.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/gqa_rotary_embedding.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/gqa_softmax.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/group_query_attention.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/prefuse_ops.cpp
  test/onnx/gen_onnx.py
  test/onnx/group_query_attention_defaults_test.onnx
  test/onnx/group_query_attention_invalid_test.onnx
  test/onnx/group_query_attention_test.onnx
  test/onnx/include/onnx_test_utils.hpp
  test/onnx/parse/group_query_attention_defaults_test.cpp
  test/onnx/parse/group_query_attention_invalid_test.cpp
  test/onnx/parse/group_query_attention_test.cpp
  test/ref/group_query_attention.cpp
  test/ref/group_query_attention_attr.cpp
  test/verify/test_group_query_attention_gen.cpp
  test/verify/test_group_query_attention_no_rotary.cpp
  test/verify/test_group_query_attention_prompt.cpp
Labels: roadmap, Perf Improve

#3520 mlir improvement for FP8 and WMMA
  requirements.txt
Labels: roadmap, high priority

#3513 Enable mlir input fusion for unary operators and dequantizelinear
  src/common.cpp
  src/include/migraphx/common.hpp
  src/targets/gpu/fuse_mlir.cpp
  test/gpu/fuse_mlir.cpp
Labels: INT4

#3521 Fixed logic error of instruction::replace()
  src/instruction.cpp
  test/instruction.cpp
Labels: bugfix

#3528 Add unpack_int4 kernel
  src/targets/gpu/jit/unpack_int4.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/unpack_int4.hpp
  src/targets/gpu/lowering.cpp
  test/ref/unpack_int4.cpp
  test/verify/main.cpp
  test/verify/test_unpack_int4.cpp
Labels: INT4

#3527 Handle more reshapes with the shape transform descriptor
  src/include/migraphx/shape_transform_descriptor.hpp
  src/shape_transform_descriptor.cpp
  test/shape_transform_descriptor.cpp
Labels: enhancement

#3539 Fix GroupQueryAttention Max Sequence Length Propagation
  src/include/migraphx/op/group_query_attention.hpp
  src/onnx/parse_group_query_attention.cpp
  src/targets/gpu/include/migraphx/gpu/group_query_attention.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/concat_past_present.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/gqa_softmax.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/prefuse_ops.cpp
  test/verify/test_group_query_attention_gen.cpp
Labels: bugfix, high priority

#3545 Add env vars for hipBLASLt
  docs/dev/env_vars.rst
Labels: documentation

#3547 MI300 specific FP8 ASM fix
  src/targets/gpu/kernels/include/migraphx/kernels/float8.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/math.hpp
Labels: bugfix, simple

#3546 Change copyright dates to 2024
  src/include/migraphx/tune_axis.hpp
  src/onnx/include/migraphx/onnx/padding.hpp
  src/onnx/padding.cpp
  src/onnx/parse_conv_transpose.cpp
  src/onnx/parse_instancenorm.cpp
  src/onnx/parse_qlinearbinary.cpp
  src/onnx/parse_qlinearconv.cpp
  src/onnx/parse_randomnormal_ops.cpp
  src/onnx/parse_randomuniform_ops.cpp
  src/onnx/parse_unique.cpp
  src/onnx/pooling.cpp
  src/targets/gpu/include/migraphx/gpu/fuse_mlir.hpp
Labels: Cleanup

#3544 Update hipblaslt_supported function to reflect hipblaslt supported architectures
  src/targets/gpu/hipblaslt.cpp
Labels: bugfix

#3556 Update BertSquad Requirements file to fix JIRA Tickets
  examples/nlp/python_bert_squad/requirements_bertsquad.txt
Labels: Cleanup

#3564 Remove the warning on using FP8 types
  src/module.cpp
  src/onnx/onnx_parser.cpp
  src/quantization.cpp
Labels: simple, Cleanup
