Repository ROCm/AMDMIGraphX, pull requests merged in 2024-04, with the labels that each got.

#2940 fix conv_concat matcher when original convolutions are grouped
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
  test/verify/test_conv_concat.cpp
Labels: bugfix

#2954 Add Stable Diffusion XL example
  examples/diffusion/README.md
  examples/diffusion/python_stable_diffusion_xl/README.md
  examples/diffusion/python_stable_diffusion_xl/clip_modifier.py
  examples/diffusion/python_stable_diffusion_xl/example_output.jpg
  examples/diffusion/python_stable_diffusion_xl/gradio_app.py
  examples/diffusion/python_stable_diffusion_xl/gradio_requirements.txt
  examples/diffusion/python_stable_diffusion_xl/requirements.txt
  examples/diffusion/python_stable_diffusion_xl/txt2img.py
Labels: skip bot checks

#2948 Change approach for loading MIGraphX shared libs - append MIGRAPHX_SO_VERSION to the name
  src/register_target.cpp
  src/version.h.in
Labels: bug, bugfix, high priority

#2951 Update Stable Diffusion 2.1 example
  examples/diffusion/python_stable_diffusion_21/README.md
  examples/diffusion/python_stable_diffusion_21/gradio_app.py
  examples/diffusion/python_stable_diffusion_21/gradio_requirements.txt
  examples/diffusion/python_stable_diffusion_21/requirements.txt
  examples/diffusion/python_stable_diffusion_21/sd21.ipynb
  examples/diffusion/python_stable_diffusion_21/txt2img.py
Labels: enhancement, skip bot checks

#2927 Broadcast with dims matcher
  src/include/migraphx/op/broadcast_with_dims.hpp
  src/simplify_dyn_ops.cpp
  test/op_shape_test.cpp
  test/simplify_dyn_ops_test.cpp
Labels: enhancement

#2799 Parse ONNX Expand to `broadcast_with_dims`
  src/CMakeLists.txt
  src/include/migraphx/op/broadcast_with_dims.hpp
  src/onnx/parse_expand.cpp
  src/simplify_dyn_ops.cpp
  test/onnx/expand_dyn_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/expand_test.cpp
  test/op_shape_test.cpp
  test/ref/broadcast_with_dims.cpp
  test/simplify_dyn_ops_test.cpp
Labels: onnx, Onnx Operators

#2975 Use so_major_version instead of so_version for migraphx shared libraries
  src/register_target.cpp
Labels: bugfix, high priority

#2961 Append so_version for loading shared libraries (changes from PR#2948 commit 7374d52a76 in develop)
  src/register_target.cpp
  src/version.h.in
Labels: bugfix

#2978 Use number of specified thread for the compilation
  src/include/migraphx/par_for.hpp
Labels: bugfix

#2980 Extract pointwise compilation logic into separate header
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_pointwise.cpp
  src/targets/gpu/include/migraphx/gpu/compile_pointwise.hpp
  src/targets/gpu/jit/pointwise.cpp
Labels: simple

#2958 Move unary operators around shape transformation
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: Perf Improve

#2982 Benchmark candidate programs instead of code objects in compile_ops
  src/include/migraphx/program.hpp
  src/program.cpp
  src/targets/gpu/compile_ops.cpp
  src/targets/gpu/include/migraphx/gpu/time_op.hpp
  src/targets/gpu/time_op.cpp
Labels: roadmap

#2957 Add support for multi outputs in pointwise ops
  src/argument.cpp
  src/cpp_generator.cpp
  src/fuse_pointwise.cpp
  src/include/migraphx/argument.hpp
  src/include/migraphx/cpp_generator.hpp
  src/include/migraphx/module.hpp
  src/include/migraphx/op/pointwise.hpp
  src/include/migraphx/pass_manager.hpp
  src/include/migraphx/program.hpp
  src/include/migraphx/raw_data.hpp
  src/include/migraphx/shape.hpp
  src/module.cpp
  src/pass_manager.cpp
  src/program.cpp
  src/shape.cpp
  src/targets/gpu/code_object_op.cpp
  src/targets/gpu/compile_gen.cpp
  src/targets/gpu/compile_pointwise.cpp
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/include/migraphx/gpu/compile_gen.hpp
  src/targets/gpu/jit/pointwise.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/functional.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/pointwise.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/print.hpp
  src/targets/gpu/kernels/include/migraphx/kernels/tuple.hpp
  test/fuse_pointwise.cpp
  test/gpu/jit.cpp
  test/op_shape_test.cpp
  test/ref/pointwise.cpp
  test/verify/test_pointwise_multi_out.cpp
Labels: roadmap, Perf Improve

#2985 fix compilation on Windows
  src/include/migraphx/argument.hpp
  src/include/migraphx/shape.hpp
Labels: bug, high priority, Windows

#2963 Fix bug with computing output shape with fused_reduce
  src/fuse_reduce.cpp
  src/targets/cpu/include/migraphx/cpu/parallel.hpp
  src/targets/gpu/jit/reduce.cpp
  test/fuse_reduce.cpp
  test/verify/test_pointwise_broadcast_reduce.cpp
Labels: bugfix

#2950 Fixing mxrfiles Windows
  src/driver/main.cpp
Labels: Windows

#2817 Fix reading cached kernels from Windows resource file
  cmake/Embed.cmake
Labels: bugfix, Windows

#2993 Limit parallelism more conservatively for constant propagate when parallel STL is not enabled
  src/propagate_constant.cpp
Labels: high priority

#2998 Update docker hub image script to support ROCm 6.1 build
  tools/docker/migraphx_with_onnxruntime_pytorch.docker
Labels: onnxruntime, dependencies, Continous Integration

#3016 Fix input args order in split module functionality
  src/module.cpp
  test/module_test.cpp
Labels: bugfix, simple

#3017 Update documentation requirements
  docs/environment.yml
  docs/sphinx/requirements.in
  docs/sphinx/requirements.txt
Labels: documentation, dependencies
