Repository ROCm/AMDMIGraphX, pull requests merged in 2024-11, with the labels that each got.

#3584 use reshape to handle flatten
  src/include/migraphx/op/flatten.hpp
  src/simplify_reshapes.cpp
  test/eliminate_contiguous_test.cpp
  test/simplify_reshapes_test.cpp
Labels: bugfix

#3587 Dont use mixed layouts with convolution
  src/CMakeLists.txt
  src/include/migraphx/layout_convolution.hpp
  src/layout_convolution.cpp
  src/module.cpp
  src/targets/cpu/target.cpp
  src/targets/gpu/target.cpp
  test/layout_convolution.cpp
Labels: roadmap, Cleanup

#3605 Prefill fix for multiple output cases
  requirements.txt
  src/targets/gpu/jit/mlir.cpp
Labels: bugfix

#3603 Fix tidy check by getting rid of unused variables.
  CMakeLists.txt
  src/module.cpp
  src/program.cpp
Labels: simple, Cleanup

#3531 Remove zero point parameter for dequantizelinear when its zero
  src/simplify_qdq.cpp
  test/quantization.cpp
  test/simplify_qdq_test.cpp
Labels: Perf Improve

#3577 Enable GEMM/dot for FP8 using hipblasLT
  src/targets/gpu/hip_gemm_impl.cpp
  src/targets/gpu/target.cpp
Labels: simple, FP8

#3609 Always output a packed type for q/dq
  src/include/migraphx/op/dequantizelinear.hpp
  src/include/migraphx/op/quantizelinear.hpp
Labels: high priority, simple

#3614 Dont use mixed layouts with convolution (#3587)
  src/CMakeLists.txt
  src/include/migraphx/layout_convolution.hpp
  src/layout_convolution.cpp
  src/module.cpp
  src/targets/cpu/target.cpp
  src/targets/gpu/target.cpp
  test/layout_convolution.cpp
Labels: high priority

#3582 Add support for unsigned types with mlir
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/mlir.cpp
  test/gpu/fuse_mlir.cpp
  test/gpu/mlir.cpp
Labels: roadmap

#3642 Add spell checker workflow
  .github/workflows/ci.yaml
Labels: Continous Integration

#3594 Compile pass for hipBLASLt
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/compile_hipblaslt.cpp
  src/targets/gpu/hip_gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/compile_hipblaslt.hpp
  src/targets/gpu/include/migraphx/gpu/hip_gemm.hpp
  src/targets/gpu/include/migraphx/gpu/hip_gemm_impl.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/target.cpp
  test/gpu/compile_hipblaslt.cpp
Labels: enhancement, roadmap, high priority

#3615 Fixed multilevel pointer conversion tidy check errors and re-enable t…
  CMakeLists.txt
  src/targets/cpu/include/migraphx/cpu/dnnl.hpp
  src/targets/gpu/kernel.cpp
  test/include/test.hpp
Labels: Cleanup

#3635 FP8OCP GFX update
  src/targets/gpu/device_name.cpp
Labels: simple

#3638 removed unused files and reorganized the index and toc.
  docs/index.rst
  docs/install/build_and_install_with_cmake.rst
  docs/install/build_and_install_with_docker.rst
  docs/install/build_and_install_with_rbuild.rst
  docs/sphinx/_toc.yml.in
Labels: documentation

#3578 Implement BF16 using generic_float class
  src/api/include/migraphx/migraphx.h
  src/include/migraphx/bf16.hpp
  src/include/migraphx/generic_float.hpp
  src/include/migraphx/shape.hpp
  src/include/migraphx/type_traits.hpp
  src/py/migraphx_py.cpp
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/hip_gemm_impl.cpp
  test/bf16.cpp
  test/gpu/jit.cpp
  test/ref/add.cpp
  test/ref/isinf.cpp
  tools/api/migraphx.h
Labels: roadmap

#3652 fix mlir attention reject flag for mi300
  src/targets/gpu/fuse_mlir.cpp
Labels: bugfix, rocMLIR

#3637 Fuse reshapes across concat
  src/simplify_reshapes.cpp
  test/simplify_reshapes_test.cpp
Labels: Matchers, Perf Improve

#3661 Remove redundant call to dead_code_elimination pass
  src/targets/gpu/target.cpp
Labels: Perf Improve

#3659 Catch invalid broadcasts in pointwise reduce fusion
  src/fuse_reduce.cpp
  test/fuse_reduce.cpp
  test/include/layernorm.hpp
  test/verify/test_layernorm.cpp
Labels: bugfix
