Repository ROCm/AMDMIGraphX, pull requests merged in 2025-02, with the labels that each got.

#3782 Move qlinear before concat to allow output fusion
  src/simplify_algebra.cpp
  src/simplify_qdq.cpp
  test/simplify_qdq_test.cpp
Labels: Perf Improve

#3798 Update Cmake since ORT 1.21 requires newer CMake
  Dockerfile
Labels: onnxruntime, simple, Continous Integration

#3801 added a link to the migraphX examples from landing page
  docs/index.rst
  docs/sphinx/_toc.yml.in
  docs/tutorials/MIGraphX-examples.rst
Labels: documentation

#3808 Force NCHW for group convolution.
  src/layout_convolution.cpp
  test/layout_convolution.cpp
Labels: high priority, Perf Improve

#3678 Add contrib groupnorm
  src/onnx/parse_groupnorm.cpp
  test/onnx/gen_onnx.py
  test/onnx/group_norm_contrib_3d_channel_last_bf16_test.onnx
  test/onnx/group_norm_contrib_3d_channel_last_half_test.onnx
  test/onnx/group_norm_contrib_3d_channel_last_test.onnx
  test/onnx/group_norm_contrib_3d_test.onnx
  test/onnx/group_norm_contrib_channels_last_3d_test.onnx
  test/onnx/group_norm_contrib_channels_last_4d_test.onnx
  test/onnx/group_norm_contrib_channels_last_and_silu_3d_test.onnx
  test/onnx/group_norm_contrib_no_activation_attr_test.onnx
  test/onnx/group_norm_contrib_no_num_groups_attr_test.onnx
  test/onnx/group_norm_contrib_silu_3d_test.onnx
  test/onnx/include/onnx_test_utils.hpp
  test/onnx/include/onnx_verify_utils.hpp
  test/onnx/parse/group_norm_contrib_3d_no_activation_err_test.cpp
  test/onnx/parse/group_norm_contrib_3d_no_num_groups_err_test.cpp
  test/onnx/parse/group_norm_contrib_3d_test.cpp
  test/onnx/parse/group_norm_contrib_channels_last_3d_test.cpp
  test/onnx/parse/group_norm_contrib_channels_last_4d_test.cpp
  test/onnx/parse/group_norm_contrib_channels_last_silu_3d_test.cpp
  test/onnx/parse/group_norm_contrib_silu_3d_test.cpp
  test/onnx/verify/group_norm_contrib_3d_bf16_test.cpp
  test/onnx/verify/group_norm_contrib_3d_half_test.cpp
  test/onnx/verify/group_norm_contrib_3d_silu_test.cpp
  test/onnx/verify/group_norm_contrib_3d_test.cpp
Labels: roadmap, high priority, Onnx Operators

#3807 Mark FP8 operations as unsupported on incompatible architectures
  src/targets/gpu/device_name.cpp
  src/targets/gpu/include/migraphx/gpu/device_name.hpp
  src/targets/gpu/target.cpp
Labels: bug, simple

#3726 Propagate layout with nonpacked inputs
  src/include/migraphx/op/binary.hpp
  test/op_shape_test.cpp
Labels: roadmap, simple, Perf Improve

#3569 Fuse reshapes on pointwise inputs for mlir output fusion
  src/targets/gpu/fuse_mlir.cpp
  test/gpu/fuse_mlir.cpp
Labels: Perf Improve, rocMLIR

#3786 Normalize standard input shapes for rocBLAS
  src/targets/gpu/gemm_impl.cpp
Labels: bugfix, high priority

#3825 Small fixes
  src/rewrite_quantization.cpp
  test/ref/quantizelinear.cpp
Labels: simple

#3829 NFC: Remove outdated comment
  src/targets/gpu/fuse_ops.cpp
Labels: skip bot checks, Cleanup

#3830 Normalize standard input shapes for hipBLASLt
  src/targets/gpu/hip_gemm_impl.cpp
Labels: roadmap, simple

#3828 Use rocBLAS by default for gfx90a instead of hipBLASLt
  docs/dev/env_vars.rst
  src/targets/gpu/device_name.cpp
  src/targets/gpu/include/migraphx/gpu/device_name.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/target.cpp
  test/gpu/compile_hipblaslt.cpp
  test/gpu/fuse_gemm.cpp
Labels: enhancement, simple

#3824 fix compilation on HIP SDK 6.3 for Windows - undefined behavior
  src/api/include/migraphx/migraphx.hpp
Labels: high priority, Windows

#3837 Use default workspace size for hipBLASLt when no algo is provided
  src/targets/gpu/hip_gemm_impl.cpp
Labels: high priority, simple

#3823 HIP SDK 6.3 for Windows bug workaround
  cmake/EnableCompilerWarnings.cmake
Labels: high priority, Windows

#3840 Add support for parsing softcap=0 to GroupQueryAttention
  src/onnx/parse_group_query_attention.cpp
  test/onnx/gen_onnx.py
  test/onnx/group_query_attention_softcap_test.onnx
  test/onnx/parse/group_query_attention_invalid_test.cpp
Labels: roadmap, Onnx Operators

#3812 Add RotaryEmbedding contrib op
  src/onnx/parse_rotary_embedding.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/rotary_embedding_errors_test.cpp
  test/onnx/rotary_embedding_cache_1_test.onnx
  test/onnx/rotary_embedding_cache_2_test.onnx
  test/onnx/rotary_embedding_dim_size_test.onnx
  test/onnx/rotary_embedding_dim_test.onnx
  test/onnx/rotary_embedding_float_test.onnx
  test/onnx/rotary_embedding_input_dims_test.onnx
  test/onnx/rotary_embedding_interleaved_large_test.onnx
  test/onnx/rotary_embedding_interleaved_test.onnx
  test/onnx/rotary_embedding_num_heads_test.onnx
  test/onnx/rotary_embedding_packed_batching_test.onnx
  test/onnx/rotary_embedding_pos_ids_1_test.onnx
  test/onnx/rotary_embedding_pos_ids_2_test.onnx
  test/onnx/rotary_embedding_pos_ids_3_test.onnx
  test/onnx/rotary_embedding_scale_test.onnx
  test/onnx/rotary_embedding_test.onnx
  test/onnx/rotary_embedding_wrong_n_inputs_test.onnx
  test/onnx/verify/rotary_embedding_test.cpp
Labels: roadmap, onnx, high priority, Onnx Operators

#3848 Raise MIGX VRM to 2.13.0
  CMakeLists.txt
Labels: dependencies

#3846 Exclude failing tests for ONNX 1.17.0
  test/py/onnx_backend_test.py
  test/py/requirements-onnx.txt
Labels: onnx, Investigate Later

#3845 Use hipblasLtMatmulAlgoGetHeuristic to get algo for workspace size
  src/targets/gpu/hip_gemm_impl.cpp
Labels: simple
