Repository ROCm/AMDMIGraphX, pull requests merged in 2025-09, with the labels that each got.

#4162 Make checking for hip flags quiet
  src/targets/gpu/compile_hip.cpp
  src/targets/gpu/hiprtc/main.cpp
  src/targets/gpu/include/migraphx/gpu/compile_hip.hpp
Labels: bugfix, Cleanup, Changelog: Resolved Issues

#4281 Compile fix, when MIOPEN is disabled: missing std includes.
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/hip_gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/gemm_impl.hpp
  src/targets/gpu/include/migraphx/gpu/hip_gemm_impl.hpp
Labels: UAI

#4287 Spelling fix for Contiguous
  src/targets/gpu/jit/mlir.cpp
Labels: bugfix, simple

#4270 fp8 quantization restricted to dot and convolution operators
  src/quantization.cpp
Labels: bugfix

#4291 Add pytorch wheels to dockerfile
  Dockerfile
Labels: Continous Integration, Changelog: Not Applicable

#4246 MXFP4 fuse_mlir changes
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/kernels/include/migraphx/kernels/fp4_casts.hpp
  test/gpu/fuse_mlir.cpp
Labels: MXFP4, Changelog: Not Applicable

#4296 Change mxfixneuron parse
  src/onnx/parse_mxfixneuron.cpp
  src/simplify_qdq.cpp
  test/onnx/parse/mxfixneuron_test.cpp
  test/simplify_qdq_test.cpp
Labels: simple

#4326 Set jenkins home dynamically
  Jenkinsfile
Labels: Changelog: Not Applicable

#4337 Fix error in MIGRAPHX_GPU_COMPILE_PARALLEL doc
  docs/reference/MIGraphX-dev-env-vars.rst
Labels: documentation, simple, skip bot checks

#4336 Update build and test script and dockerfile to add in onnxrt pai laun…
  Dockerfile
  test/onnx/.onnxrt-commit
  tools/build_and_test_onnxrt.sh
Labels: bugfix, Continous Integration
