Repository ROCm/AMDMIGraphX, pull requests merged in 2025-01, with the labels that each got.

#3723 Enable cpp core guidlines checks.
  CMakeLists.txt
  src/include/migraphx/program.hpp
  src/program.cpp
  test/ref/add.cpp
Labels: Cleanup

#3740 Fix docs, add netron output docs
  docs/driver/read.rst
  docs/migraphx-driver.rst
  docs/reference/driver-options.rst
Labels: simple, skip bot checks

#3748 Fix broken compilation on Windows
  src/include/migraphx/base64.hpp
Labels: bugfix, Windows, UAI

#3744 Update LICENSE to 2025
  LICENSE
Labels: documentation

#3684 FP8 OCP to FP8 FNUZ on hardware with only FP8 FNUZ support
  src/CMakeLists.txt
  src/cpp_generator.cpp
  src/fp8_ocp_to_fnuz.cpp
  src/include/migraphx/fp8_ocp_to_fnuz.hpp
  src/include/migraphx/match/dq_helpers.hpp
  src/include/migraphx/op/bit_cast.hpp
  src/simplify_qdq.cpp
  src/targets/gpu/target.cpp
  test/fp8_ocp_to_fnuz_test.cpp
  test/include/quantize_helpers.hpp
  test/ref/fp8_ocp_to_fnuz.cpp
  test/simplify_qdq_test.cpp
  test/verify/test_fp8_ocp_to_fnuz_gemm.cpp
Labels: roadmap, FP8

#3742 Update fuse gemm test to use get_compute_fp32_flag() function
  test/gpu/fuse_gemm.cpp
Labels: simple, Continous Integration

#3758 fix attn fusion when trailing pointwise has literal
  src/targets/gpu/fuse_mlir.cpp
Labels: bugfix, simple

#3650 Add MultiHeadAttention
  src/onnx/parse_multi_head_attention.cpp
  test/onnx/gen_onnx.py
  test/onnx/mha_cross_attention_test.onnx
  test/onnx/mha_invalid_attribute_test.onnx
  test/onnx/mha_invalid_cross_key_test.onnx
  test/onnx/mha_invalid_cross_value_test.onnx
  test/onnx/mha_invalid_input_test.onnx
  test/onnx/mha_invalid_key_missing_test.onnx
  test/onnx/mha_invalid_key_ndim_test.onnx
  test/onnx/mha_invalid_key_test.onnx
  test/onnx/mha_invalid_kv_test.onnx
  test/onnx/mha_invalid_qkv_test.onnx
  test/onnx/mha_invalid_query_test.onnx
  test/onnx/mha_invalid_value_missing_test.onnx
  test/onnx/mha_invalid_value_ndim_test.onnx
  test/onnx/mha_invalid_value_test.onnx
  test/onnx/mha_kv_packed_test.onnx
  test/onnx/mha_qkv_packed_test.onnx
  test/onnx/mha_scale_test.onnx
  test/onnx/mha_test.onnx
  test/onnx/parse/mha_cross_attention_test.cpp
  test/onnx/parse/mha_invalid_tests.cpp
  test/onnx/parse/mha_kv_packed_test.cpp
  test/onnx/parse/mha_qkv_packed_test.cpp
  test/onnx/parse/mha_test.cpp
  test/onnx/verify/mha_cross_attention_test.cpp
  test/onnx/verify/mha_kv_packed_test.cpp
  test/onnx/verify/mha_qkv_packed_test.cpp
  test/onnx/verify/mha_scale_test.cpp
  test/onnx/verify/mha_test.cpp
Labels: roadmap, Onnx Operators

#3529 Fixed a broken link and removed unused topics
  docs/install/installing_with_package.rst
Labels: documentation

#3757 Fix memory_coloring pass when MIGRAPHX_NSTREAMS > 2
  src/memory_coloring.cpp
  test/memory_coloring_test.cpp
Labels: bugfix, simple

#3724 Update API to break out fp8 quantization functionality.
  src/api/api.cpp
  src/api/include/migraphx/migraphx.h
  src/api/include/migraphx/migraphx.hpp
  src/api/migraphx.py
  src/py/migraphx_py.cpp
  test/api/test_cpu.cpp
  test/gpu/quantization.cpp
  tools/api/api.cpp
  tools/api/migraphx.h
Labels: roadmap, onnxruntime

#3763 ConvInteger: fix parsing for x_zero_point and w_zero_point
  src/onnx/parse_convolution.cpp
  src/simplify_algebra.cpp
  test/onnx/convinteger_bias_test.onnx
  test/onnx/convinteger_dual_bias_simple_test.onnx
  test/onnx/convinteger_dual_bias_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/convinteger_bias_test.cpp
  test/onnx/parse/convinteger_dual_bias_test.cpp
  test/onnx/verify/quant_convolution_dual_bias_test.cpp
  test/onnx/verify/quant_convolution_mismatched_input_dual_bias_test.cpp
Labels: bugfix, simple

#3715 Driver quantize fp8 update
  src/quantization.cpp
  src/targets/gpu/include/migraphx/gpu/context.hpp
  test/gpu/context_serialize.cpp
Labels: simple

#3731 Optimize CPU and Memory performance for Resize linear mode parser
  src/onnx/parse_resize.cpp
Labels: high priority, Perf Improve

#3773 Resize onnx operator: Optimization for Compute and Space performance of its linear option.
  src/onnx/parse_resize.cpp
  test/onnx/gen_onnx.py
  test/onnx/include/onnx_test_utils.hpp
  test/onnx/parse/resize_downsample_linear_test.cpp
  test/onnx/parse/resize_upsample_linear_test.cpp
  test/onnx/parse/upsample_linear_test.cpp
  test/onnx/resize_upsample_linear_large_test.onnx
Labels: enhancement, Perf Improve
