Repository ROCm/AMDMIGraphX, pull requests merged in 2025-08, with the labels that each got.

#4187 Netron Output Param Name
  src/netron_output.cpp
Labels: simple

#4214 Graphviz output improvement (node color change)
  src/driver/main.cpp
  src/graphviz.cpp
  src/include/migraphx/graphviz.hpp
  src/include/migraphx/op/binary.hpp
  src/include/migraphx/op/broadcast.hpp
  src/include/migraphx/op/broadcast_for_dot.hpp
  src/include/migraphx/op/broadcast_with_dims.hpp
  src/include/migraphx/op/convolution.hpp
  src/include/migraphx/op/pointwise.hpp
  src/include/migraphx/op/pooling.hpp
  src/include/migraphx/op/reduce_op.hpp
  src/include/migraphx/op/slice.hpp
  src/include/migraphx/op/unary.hpp
  test/print_graph_test.cpp
Labels: enhancement

#4211 Update any_ptr assertion to not fail when running on default hip stream
  src/include/migraphx/any_ptr.hpp
Labels: bugfix, simple

#4216 Add matcher to upcast base softmax ops
  src/rewrite_reduce.cpp
  test/rewrite_reduce.cpp
Labels: high priority

#4229 Reduce nested visits in ref operators to improve compilation time
  src/argument.cpp
  src/include/migraphx/argument.hpp
  src/include/migraphx/op/gathernd.hpp
  src/include/migraphx/op/group_query_attention.hpp
  src/include/migraphx/op/multinomial.hpp
  src/include/migraphx/op/nonmaxsuppression.hpp
  src/include/migraphx/op/quant_convolution.hpp
  src/include/migraphx/op/rnn_variable_seq_lens.hpp
Labels: simple, Cleanup, Perf Improve

#4201 Byte class and Refactor to/from GPU
  src/generate.cpp
  src/include/migraphx/byte.hpp
  src/include/migraphx/raw_data.hpp
  src/include/migraphx/shape.hpp
  src/include/migraphx/tensor_view.hpp
  src/shape.cpp
  src/targets/gpu/hip.cpp
  src/targets/gpu/include/migraphx/gpu/compiler.hpp
  test/argument_test.cpp
  test/byte_test.cpp
  test/generate.cpp
  test/shape_test.cpp
Labels: MXFP4

#4200 Add python API for returning serialized bytes
  src/py/migraphx_py.cpp
  test/py/test_save_load.py
Labels: simple, python

#4258 Bump Doxygen to 1.14.0
  Dockerfile
Labels: Continous Integration
