Repository ROCm/AMDMIGraphX, pull requests merged in 2025-04, with the labels that each got.

#3907 Add warnings and comments for ONNX 1.17.0 backend tests
  src/onnx/parse_resize.cpp
  test/py/onnx_backend_test.py
Labels: bugfix, simple, Cleanup

#3928 fixed link
  docs/install/installing_with_package.rst
Labels: documentation

#3935 Add QuickGelu ORT contrib op
  src/onnx/parse_gelu.cpp
  test/onnx/gelu_add_bias_test.onnx
  test/onnx/gelu_bias_invalid_type_test.onnx
  test/onnx/gelu_fast_bias_test.onnx
  test/onnx/gelu_fast_invalid_bias_test.onnx
  test/onnx/gelu_fast_invalid_x_test.onnx
  test/onnx/gelu_fast_test.onnx
  test/onnx/gelu_quick_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/gelu_quick_test.cpp
  test/onnx/verify/gelu_quick_test.cpp
Labels: roadmap, Onnx Operators

#3934 Re-enable fp8ocp dot on gfx950
  src/targets/gpu/target.cpp
Labels: simple, FP8

#3937 Use string_value to see if the variable is set for gfx_default_rocblas()
  src/targets/gpu/device_name.cpp
Labels: bugfix, simple

#3917 Adding skip-layer-normalization operator
  src/onnx/parse_skip_layer_normalization.cpp
  test/onnx/gen_onnx.py
  test/onnx/include/onnx_test_utils.hpp
  test/onnx/parse/skip_layer_normalization_2d_skip_test.cpp
  test/onnx/parse/skip_layer_normalization_beta_bias_test.cpp
  test/onnx/parse/skip_layer_normalization_beta_test.cpp
  test/onnx/parse/skip_layer_normalization_invalid_beta_test.cpp
  test/onnx/parse/skip_layer_normalization_invalid_bias_test.cpp
  test/onnx/parse/skip_layer_normalization_invalid_input_test.cpp
  test/onnx/parse/skip_layer_normalization_invalid_n_args_test.cpp
  test/onnx/parse/skip_layer_normalization_skip_batch_size_1_test.cpp
  test/onnx/parse/skip_layer_normalization_test.cpp
  test/onnx/skip_layer_normalization_2d_skip_test.onnx
  test/onnx/skip_layer_normalization_beta_bias_test.onnx
  test/onnx/skip_layer_normalization_beta_test.onnx
  test/onnx/skip_layer_normalization_invalid_beta_test.onnx
  test/onnx/skip_layer_normalization_invalid_bias_test.onnx
  test/onnx/skip_layer_normalization_invalid_input_test.onnx
  test/onnx/skip_layer_normalization_invalid_n_args_test.onnx
  test/onnx/skip_layer_normalization_skip_batch_size_1_test.onnx
  test/onnx/skip_layer_normalization_test.onnx
  test/onnx/verify/skip_layer_normalization.cpp
Labels: enhancement, Onnx Operators

#3947 update docs (#3858)
  docs/dev/quantization.rst
  docs/driver/compile.rst
  docs/migraphx-driver.rst
  docs/reference/cpp.rst
  docs/reference/py.rst
Labels: documentation

#3949 Test License Checker and Fix Files
  test/include/quantize_helpers.hpp
  tools/check_stamped.py
  tools/converters/mxr_to_onnx.py
Labels: simple, Cleanup

#3882 Fix Windows compiler warnings (#3880)
  cmake/EnableCompilerWarnings.cmake
  src/CMakeLists.txt
  src/api/CMakeLists.txt
Labels: roadmap

#3955 Use time_loop function to measure time for exhaustive tune runs
  src/targets/gpu/hip_gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/time_op.hpp
  src/targets/gpu/time_op.cpp
Labels: enhancement

#3956 Port to Windows the Python bindings for MIGraphX
  CMakeLists.txt
  cmake/PythonModules.cmake
  src/py/py.cpp
Labels: Windows

#3974 Fix compilation with hiBLASLt on Windows
  CMakeLists.txt
  src/targets/gpu/include/migraphx/gpu/hip_gemm.hpp
  src/targets/gpu/include/migraphx/gpu/hip_gemm_impl.hpp
  src/targets/gpu/include/migraphx/gpu/hipblaslt.hpp
Labels: Windows
