Repository ROCm/AMDMIGraphX, pull requests merged in 2025-06, with the labels that each got.

#4039 Fix docstring for layout op
  src/include/migraphx/op/layout.hpp
Labels: documentation, simple, skip bot checks

#4050 Fix generic_float template params
  src/include/migraphx/generic_float.hpp
  src/include/migraphx/half.hpp
Labels: simple, Cleanup

#4073 nonmaxsuppression: identical boxes/scores not ordered correctly
  src/include/migraphx/op/nonmaxsuppression.hpp
  test/ref/nonmaxsuppression.cpp
Labels: bugfix, Cleanup

#4062 Add assert for missing jit op
  src/targets/gpu/compiler.cpp
Labels: bugfix, simple

#3924 Enable debug assertions in libstdc++
  Jenkinsfile
  src/fuse_concat.cpp
  src/include/migraphx/instruction_ref.hpp
  src/include/migraphx/iterator.hpp
  src/include/migraphx/op/name.hpp
  src/instruction.cpp
  test/tf/tests/assert_less_equal_test.cpp
Labels: high priority, Continous Integration, Cleanup

#4072 Add edge padding mode
  src/onnx/parse_pad.cpp
  test/onnx/gen_onnx.py
  test/onnx/pad_edge_1d_test.onnx
  test/onnx/pad_edge_2d_test.onnx
  test/onnx/pad_edge_2d_with_axes_test.onnx
  test/onnx/parse/pad_edge_1d_test.cpp
  test/onnx/parse/pad_edge_2d_test.cpp
  test/onnx/parse/pad_edge_2d_with_axes_test.cpp
  test/onnx/verify/pad_edge_1d_test.cpp
  test/onnx/verify/pad_edge_2d_test.cpp
Labels: enhancement, Onnx Operators

#4089 Fix check for scales if presenting roi in Resize op
  src/onnx/parse_resize.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/resize_roi_skip_test.cpp
  test/onnx/resize_downsample_f_dyn2_test.onnx
  test/onnx/resize_downsample_f_ref2_test.onnx
  test/onnx/resize_roi_skip_test.onnx
Labels: bugfix

#4055 Add TF AddN op support
  src/tf/parse_addn.cpp
  test/tf/gen_tf_pb.py
  test/tf/models/addn_single_test.pb
  test/tf/models/addn_test.pb
  test/tf/tests/addn_test.cpp
Labels: Tensorflow, Tensorflow Operators

#4084 Print Kernel/Module in Compile Failure
  src/targets/gpu/compile_ops.cpp
  src/targets/gpu/include/migraphx/gpu/tuning_config.hpp
  src/targets/gpu/mlir.cpp
Labels: enhancement
