Repository ROCm/AMDMIGraphX, pull requests merged in 2025-05, with the labels that each got.

#3984 Add onnx runtime python driver
  tools/ort/README.md
  tools/ort/ort_driver.py
  tools/ort/requirements.txt
Labels: enhancement, onnxruntime, high priority, Continous Integration

#3985 Remove rocblas fp8
  src/targets/gpu/CMakeLists.txt
  src/targets/gpu/device_name.cpp
  src/targets/gpu/gemm_impl.cpp
  src/targets/gpu/include/migraphx/gpu/rocblas.hpp
  src/targets/gpu/rocblas.cpp
  src/targets/gpu/target.cpp
Labels: FP8

#3992 Fix compilation after merging #3905
  cmake/Embed.cmake
  src/CMakeLists.txt
  src/targets/gpu/CMakeLists.txt
  test/gpu/quantization.cpp
  test/include/test.hpp
  test/onnx/CMakeLists.txt
  test/quantization.cpp
  test/ref/fill.cpp
  test/ref/multinomial.cpp
  test/ref/random_uniform.cpp
  test/ref/unique.cpp
  test/ref_dev_examples.cpp
  test/tf/CMakeLists.txt
Labels: bugfix, high priority, Windows

#3999 Ignore virtual environments when building Python modules + regression fix
  cmake/PythonModules.cmake
Labels: bugfix, Windows

#3993 Dont fold mul with gemm when the gemm is used more than once
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: enhancement, high priority, simple, Matchers

#3991 Move rewrite_rnn before the eliminate_data_type passes
  src/targets/gpu/target.cpp
Labels: simple

#3953 find_splits::is_dependent refactor
  src/include/migraphx/instruction.hpp
  src/instruction.cpp
  src/simplify_algebra.cpp
Labels: Perf Improve

#3959 Refactor License and Format Files
  LICENSE
  tools/check_stamped.py
  tools/format.py
  tools/git_tools.py
  tools/license_stamper.py
  tools/stamp_status.py
Labels: Continous Integration, Cleanup

#3990 Have fp8 GEMMs go to hipblaslt only
  src/targets/gpu/device_name.cpp
  src/targets/gpu/hipblaslt.cpp
  src/targets/gpu/include/migraphx/gpu/device_name.hpp
  src/targets/gpu/include/migraphx/gpu/hipblaslt.hpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/target.cpp
Labels: FP8

#4010 Parse resize fix: only check "keep_aspect_ratio_policy" attribute for sizes input
  src/onnx/parse_resize.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/resize_aspect_ratio_err_test.cpp
  test/onnx/resize_aspect_ratio_err_test.onnx
Labels: bugfix, simple

#4009 Remove DPP for v_add_f64 as it is unsupported
  src/targets/gpu/kernels/include/migraphx/kernels/reduce.hpp
Labels: bugfix

#3996 Fix compilation with hipBLASLt OFF
  src/targets/gpu/include/migraphx/gpu/device_name.hpp
Labels: bugfix, Windows

#4020 Fix bug with reshape_lazy in MLIR
  src/simplify_reshapes.cpp
  src/targets/cpu/lowering.cpp
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/mlir.cpp
  test/gpu/fuse_mlir.cpp
Labels: bugfix

#4022 Ignore empty strings when checking if onnx graph is sorted
  src/onnx/onnx_parser.cpp
Labels: bugfix, simple

#2853 Add propagate_precision pass
  src/CMakeLists.txt
  src/include/migraphx/propagate_precision.hpp
  src/include/migraphx/shape.hpp
  src/propagate_precision.cpp
  src/targets/gpu/target.cpp
  test/propagate_precision.cpp
Labels: Perf Improve

#4030 Push ORT tests to ort label
  Jenkinsfile
Labels: onnxruntime, Continous Integration

#4023 Add quantize_bf16 to C/python api output
  src/api/api.cpp
  src/api/include/migraphx/migraphx.h
  src/api/include/migraphx/migraphx.hpp
  src/api/migraphx.py
  tools/api/api.cpp
Labels: enhancement, roadmap

#4033 Fix test failure in test_fuse_pointwise
  src/fuse_pointwise.cpp
  src/instruction.cpp
Labels: bugfix

#4019 fixed dimension mismatching by adding reshape op for zero scalar
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: bugfix

#4032 Code comments update
  src/include/migraphx/matcher.hpp
  src/include/migraphx/module.hpp
  src/include/migraphx/op/layout.hpp
  src/include/migraphx/shape.hpp
  src/module.cpp
  src/targets/gpu/fuse_mlir.cpp
Labels: documentation, simple, skip bot checks
