Repository ROCm/AMDMIGraphX, pull requests merged in 2025-03, with the labels that each got.

#3856 Remove rocBLAS bug workaround for solution index
  src/targets/gpu/rocblas.cpp
Labels: roadmap, simple, Cleanup

#3729 Layout convolution as NHWC or NCHW only
  src/layout_convolution.cpp
  test/layout_convolution.cpp
Labels: roadmap, simple

#3871 navi32 support for jenkins
  Jenkinsfile
Labels: Continous Integration, Cleanup

#3880 Fix Windows compiler warnings
  cmake/EnableCompilerWarnings.cmake
Labels: Windows

#3903 Eliminate fp8 gemm on gfx950
  src/targets/gpu/target.cpp
  test/verify/run_verify.cpp
Labels: simple
