Repository ROCm/AMDMIGraphX, pull requests merged in 2025-10, with the labels that each got.

#4340 Add video and render groups in docker for CI
  Jenkinsfile
Labels: bugfix, high priority, Continous Integration

#4324 Fix MXFP4 bugs
  src/include/migraphx/raw_data.hpp
  src/propagate_constant.cpp
  src/simplify_qdq.cpp
  test/propagate_constant_test.cpp
  test/simplify_qdq_test.cpp
Labels: roadmap, bugfix

#4301 Brevitas MXFP4 quantization parse
  src/onnx/onnx_parser.cpp
  src/onnx/parse_dynamicscale.cpp
  src/onnx/parse_quantizelinear.cpp
  test/onnx/dynamicscale_even_test.onnx
  test/onnx/dynamicscale_odd_test.onnx
  test/onnx/dynamicscale_small_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/dynamicscale_test.cpp
  test/onnx/parse/quantizelinear_mx_type_test.cpp
  test/onnx/quantizelinear_mxfp4_even_test.onnx
  test/onnx/quantizelinear_mxfp4_odd_test.onnx
  test/onnx/verify/dynamicscale_small_test.cpp
Labels: roadmap, onnx, high priority

#4261 Fuse GEMM+GEMM with rocMLIR
  Jenkinsfile
  docs/reference/MIGraphX-dev-env-vars.rst
  src/include/migraphx/module.hpp
  src/module.cpp
  src/targets/gpu/fuse_mlir.cpp
  test/gpu/fuse_mlir.cpp
  test/module_test.cpp
  test/verify/CMakeLists.txt
  test/verify/test_conv_add_dot.cpp
  test/verify/test_dot_add_dot.cpp
Labels: enhancement, Matchers, rocMLIR

#4333 Update CI to 7.0
  .github/workflows/benchmark.yaml
  .github/workflows/config.md
  .github/workflows/performance.yaml
  .github/workflows/rocm-image-release.yaml
  .github/workflows/sync_rocMLIR.yaml
  .github/workflows/unreleased_rocm.yaml
  CMakeLists.txt
  Dockerfile
  hip-clang.docker
  src/include/migraphx/operation.hpp
  src/include/migraphx/pass.hpp
  tools/docker/sles.docker
Labels: Continous Integration
