Repository ROCm/AMDMIGraphX, pull requests merged in 2025-07, with the labels that each got.

#4106 Adding back memory check
  src/targets/gpu/hip.cpp
Labels: Windows

#4083 Update 6.4 GQA tests
  Dockerfile
  src/CMakeLists.txt
  src/include/migraphx/op/group.hpp
  src/include/migraphx/operators.hpp
  src/targets/gpu/fuse_mlir.cpp
  src/targets/gpu/lowering.cpp
  src/targets/gpu/prefuse_ops.cpp
  src/targets/gpu/time_op.cpp
  test/onnx/.onnxrt-commit
  test/op_shape_test.cpp
  test/verify/test_group_query_attention_gen_small.cpp
  test/verify/test_group_query_attention_no_rotary.cpp
  test/verify/test_group_query_attention_prompt.cpp
Labels: Continous Integration, Cleanup

#4104 Fixed the wrong graph connections for the unordered nodes
  src/onnx/onnx_parser.cpp
  test/onnx/conv_bn_relu_maxpool_unordered_nonvalue_optional_ios_test.onnx
  test/onnx/gen_onnx.py
  test/onnx/parse/conv_bn_relu_maxpool_test.cpp
Labels: bugfix, simple

#4114 Deleting function and call to it as per comment from HIP team
  src/targets/gpu/hip.cpp
Labels: WCR

#4123 Skip horizontal fusion when we would concat a constant across a broadcasted axis
  src/simplify_algebra.cpp
  test/simplify_algebra_test.cpp
Labels: WCR

#4119 Remove operators on empty literals in dead_code_elimination
  src/dead_code_elimination.cpp
  src/instruction.cpp
  test/dead_code_elimination_test.cpp
Labels: bugfix, WCR

#4115 Support additional types for linear Resize op
  src/onnx/parse_resize.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/resize_downsample_linear_half_test.cpp
  test/onnx/resize_downsample_linear_half_test.onnx
  test/onnx/verify/resize_downsample_linear_half_test.cpp
Labels: bugfix, WCR

#4133 Fix parse resize when input and output shapes are same
  src/onnx/parse_resize.cpp
Labels: bugfix, simple

#4110 Print Kernel/Module in Compile Failure
  src/targets/gpu/compile_ops.cpp
  src/targets/gpu/include/migraphx/gpu/tuning_config.hpp
  src/targets/gpu/mlir.cpp
Labels: enhancement

#4135 Always print in tests even when it is not printable
  src/include/migraphx/instruction_ref.hpp
  test/analyze_streams.cpp
  test/api/test_array_base.cpp
  test/api/test_assign.cpp
  test/api/test_cpu.cpp
  test/api/test_custom_op.cpp
  test/api/test_custom_op_gpu.cpp
  test/api/test_dynamic_shape.cpp
  test/api/test_gpu.cpp
  test/api/test_lookup.cpp
  test/api/test_module_construct.cpp
  test/api/test_save_load.cpp
  test/eval_test.cpp
  test/fp8e4m3fn.cpp
  test/fp8e4m3fnuz.cpp
  test/fp8e5m2.cpp
  test/fp8e5m2fnuz.cpp
  test/include/test.hpp
  test/matcher.cpp
  test/module_test.cpp
  test/output_alias.cpp
  test/simplify_reshapes_test.cpp
  test/transform_view.cpp
  test/validate.cpp
  test/value_test.cpp
Labels: Cleanup

#4145 Update failing GQA tests
  test/verify/test_group_query_attention_gen.cpp
  test/verify/test_group_query_attention_prompt.cpp
Labels: bugfix

#4160 Move CI to 6.4.2
  .github/workflows/benchmark.yaml
  .github/workflows/config.md
  .github/workflows/performance.yaml
  .github/workflows/rocm-image-release.yaml
  .github/workflows/sync_rocMLIR.yaml
  .github/workflows/unreleased_rocm.yaml
  Dockerfile
  hip-clang.docker
  tools/docker/sles.docker
  tools/docker/ubuntu_2204.dockerfile
Labels: roadmap, Continous Integration

#4156 Workaround for cmake 4.0+
  requirements.txt
Labels: bugfix, backport

#4155 [rocm7.0] Fix parse resize when input and output shapes are same (#4133) (#4161)
  src/onnx/parse_resize.cpp
  test/onnx/gen_onnx.py
  test/onnx/parse/resize_with_same_inout_shapes_test.cpp
  test/onnx/resize_with_same_inout_shapes_test.onnx
Labels: roadmap

#4143 Refactor iota_iterator
  src/include/migraphx/bit_cast.hpp
  src/include/migraphx/iota_iterator.hpp
  src/include/migraphx/iterator.hpp
  src/include/migraphx/par_for.hpp
  src/include/migraphx/ranges.hpp
  src/include/migraphx/tensor_view.hpp
  test/iota_iterator.cpp
Labels: enhancement, roadmap, bugfix, Cleanup

#4182 Check for hipblaslt workspace size during tuning
  src/targets/gpu/hip_gemm_impl.cpp
Labels: bugfix, high priority, backport
